import type { ManualTopic } from './types';

export const adminTopics: ManualTopic[] = [
  {
    id: 'admin-sign-in-out',
    title: 'Sign in to and leave the admin portal',
    purpose: 'Open the protected administrator workspace and safely end your session.',
    where: 'Admin sign-in at /admin/login; profile menu → Logout',
    who: 'Administrators with an active admin-role account.',
    prerequisites: ['Use your assigned administrator email and password. Member and provider credentials do not grant administrator access.'],
    steps: [
      'Open /admin/login and enter your administrator email and password.',
      'Choose Sign in. If a message appears, correct the credentials or ask the administrator responsible for your account for help.',
      'After successful sign-in, use the top navigation to open your workspace. Protected direct links and browser refresh still require an administrator session.',
      'When finished, open the profile menu at the top right and choose Logout. Confirm that the administrator sign-in page appears before leaving a shared device.',
    ],
    result: 'An authorized administrator can use the portal; signing out returns to administrator sign-in.',
    restrictions: ['There is no self-service administrator password-recovery form in this portal. Never share your credentials or an emailed account-access link.'],
  },
  {
    id: 'admin-navigation',
    title: 'Find an admin workspace',
    purpose: 'Use the admin navigation to open registrations, directory, enquiries, logs, and settings workflows.',
    where: 'Admin portal → top navigation and profile menu',
    who: 'Administrators with an active admin-role account.',
    prerequisites: ['Sign in to the admin portal with an account that has the admin role.'],
    steps: [
      '1. Use Registrations to open registered member accounts.',
      '2. Open Directory Management to choose Providers, Provider applications, Specializations, Languages, Invitations, or Reviews.',
      '3. Open Enquiries to choose Subscribers, Contact Enquiries, or Platform feedback.',
      '4. Open the profile menu for User Manual immediately below your identity details, followed by Analytics, Activity Logs, Email Logs, Settings, and Logout.',
      '5. Use a detail page breadcrumb or back link to return to its associated list.',
    ],
    result: 'The selected admin workspace opens within the protected admin portal.',
    restrictions: [
      'Admin workspaces require the admin role; provider and member accounts use separate portals.',
      'Dashboard and Analytics workflows are intentionally documented outside this admin-workflows guide.',
    ],
  },
  {
    id: 'admin-registrations',
    title: 'Review registered accounts',
    purpose: 'Find a public member registration and inspect its submitted account and verification details.',
    where: 'Admin portal → Registrations',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Open Registrations from the top navigation.',
      '2. Search by member name or email; open Filters to narrow by Horse Owner or Stable Manager role, or verified/unverified email.',
      '3. Use pagination to move between pages or change the page size.',
      '4. Open a row’s Actions menu and choose View details.',
      '5. Review name, email, mobile, roles, country, city, email-verification state and timestamp, and registration date; choose Close or press Escape to return.',
    ],
    result: 'The selected account is available for administrative review.',
    restrictions: [
      'This workflow is read-only: it does not edit a member profile, change roles, verify email, or suspend an account.',
      'Use personal information only for authorized administrative purposes.',
    ],
  },
  {
    id: 'provider-directory',
    title: 'Find and manage providers in the directory',
    purpose: 'Locate a hospital, clinic, or doctor and use available review, status, publication, and access actions.',
    where: 'Admin portal → Directory Management → Providers',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Search providers by name. Open Filters to narrow by provider type, Stable visit, Emergency services available, Status, or Publication; remove a filter chip or choose Clear all filters to reset.',
      '2. Review provider name and type, visit and emergency indicators, available contact, rating, review count, status, publication, and creation date. Choose a review-count link to open Reviews scoped to that provider.',
      '3. Use pagination to browse results. Choose a provider name or Actions → View to open the profile; choose Edit to open its wizard.',
      '4. For an Under review provider, choose Approve provider when available. Read the result notice and choose Retry approval email only if offered.',
      '5. For a record not Under review, choose Activate or Deactivate to change operational status. Choose Publish or Unpublish separately to change directory visibility.',
      '6. Choose Add provider to start a new record.',
    ],
    result: 'The selected provider profile, operational status, and publication state can be managed independently.',
    restrictions: [
      'Under review records have an Approve provider action instead of the normal Activate/Deactivate action.',
      'Active status and Published status are separate; changing one does not change the other.',
      'Approval email delivery can fail after approval. The provider remains approved; a retry addresses delivery, not the approval decision.',
    ],
  },
  {
    id: 'provider-record-details',
    title: 'Review a provider record',
    purpose: 'Read the saved provider overview and identify the detail sections for professional information, services, locations, trips, and photos.',
    where: 'Admin portal → Directory Management → Providers → provider name or Actions → View',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Open the correct provider from the directory.'],
    steps: [
      '1. In Overview, confirm the provider type, status (Under review, Active, or Inactive), publication state (Published or Unpublished), and Stable / Not stable indicator.',
      '2. Review the summary fields Email, Phone, Website, Years of experience, Created, and Updated.',
      '3. For a Doctor / Vet, inspect Professional info and Qualifications. Use Services & languages and Specializations to review the provider’s offered services and linked directory terms.',
      '4. Review Locations to identify the primary address and any additional locations. For a doctor, review Doctor trips and its recorded date periods.',
      '5. Review Photos, including image metadata and which image is marked Profile photo.',
      '6. Use Edit to open the profile wizard or the relevant section’s controls to manage collections. Use the separate portal-access, visit, photo, lifecycle, and review workflows when those actions are needed.',
    ],
    result: 'The selected provider’s current administrative overview and available profile sections are available for review.',
    restrictions: [
      'This page reflects the currently saved provider record; it does not display an unsaved wizard draft.',
      'Under review, active status, and publication are distinct states. Review each badge rather than assuming one implies another.',
      'Doctor-only information and Doctor trips are not available for Hospital or Clinic records.',
    ],
  },
  {
    id: 'provider-create',
    title: 'Create a provider',
    purpose: 'Create a hospital, clinic, or doctor directory record with its initial profile, service, contact, and location information.',
    where: 'Admin portal → Directory Management → Providers → Add provider',
    who: 'Administrators',
    prerequisites: [
      'Sign in with an admin-role account.',
      'Have approved provider information and at least one valid primary email ready.',
      'Active specialization and language catalogs must load so their values can be selected.',
    ],
    steps: [
      '1. In Basic details, choose Provider type (Hospital, Clinic, or Doctor / Vet), enter Provider / practice name, and optionally add Website. For a hospital or clinic, enter Years of experience (0–100) and optional Description. Select applicable Specializations and Languages.',
      '2. Optionally select a Profile photo. JPEG, PNG, GIF, and WebP are supported, up to 10 MB.',
      '3. For Doctor / Vet, complete the doctor-only Professional details step: required First name and Last name; optionally add Professional title, Years of experience (0–100), Biography, Experience notes, and qualifications with Title, Institution, and Year.',
      '4. In Services, choose Stable visit. If enabled, enter a maximum working radius greater than 0 km. Choose Emergency services available only when appropriate and provide its required emergency contact number.',
      '5. For Doctor / Vet, choose Ongoing or Visiting availability. A Visiting doctor may leave the initial visit blank or complete its location and both dates.',
      '6. Set Status (Active or Inactive) and Publication status (Unpublished or Published) independently.',
      '7. In Contact & location, enter at least one valid primary email; add optional phone numbers and additional emails, marking one primary in each collection. Enter the primary location: Country, City, Address line 1, and Pincode / postal code are required for a new provider.',
      '8. Review the information and return to a section to correct it. Optionally enable Send portal access email after creating this provider and choose a valid contact email.',
      '9. Choose Create provider and wait for the saved provider profile. If only photo upload fails, choose Retry photo upload or Edit saved provider rather than submitting a duplicate.',
    ],
    result: 'The provider record is created with its profile, relationships, services, status, visibility, contacts, and primary location. Any requested portal-email result is reported separately.',
    restrictions: [
      'Provider type and provider/practice name are required. Doctor / Vet records also require first and last names.',
      'A new record requires a primary email and complete primary location. Stable-visit providers require a positive maximum radius; enabling emergency services requires an emergency number.',
      'An initial doctor visit must have a location and both dates, and its end date cannot precede its start date. Leave visit fields blank to create a Visiting doctor without a scheduled period.',
      'A photo-upload failure can happen after the provider record is saved. Retry the photo or edit that record; do not create the provider again.',
      'Portal access is optional and requires a valid provider email. Email delivery may fail even when provider creation succeeds.',
    ],
  },
  {
    id: 'provider-edit',
    title: 'Edit a provider profile',
    purpose: 'Update an existing provider’s editable fields and review changes before saving.',
    where: 'Admin portal → Directory Management → Providers → select provider → Edit',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Open the correct provider record and confirm the information to change.'],
    steps: [
      '1. Open the provider and choose Edit. The wizard loads saved values, including contacts, relationships, doctor details, and the primary location.',
      '2. In Basic details, update Provider type, Provider / practice name, Website, and (for a hospital or clinic) Description. Select or clear Specializations and Languages; choose a new profile photo if needed.',
      '3. For a doctor, update First name, Last name, Professional title, Years of experience, Biography, Experience notes, and qualifications. Each qualification needs a Title. Update doctor availability if needed.',
      '4. Update Stable visit and its maximum working radius, Emergency services available and emergency contact number, Status, and Publication status as needed.',
      '5. In Contact & location, add, edit, remove, or mark a primary email or phone. Update the primary location’s name, address lines, city, state/province, country, postal code, latitude, or longitude.',
      '6. Continue through the wizard and inspect Review & save. Use its edit controls to return to a section; choose Save changes after reviewing the record.',
      '7. Return to the provider profile and confirm the saved values and relationship changes.',
    ],
    result: 'The provider detail page reflects the saved changes.',
    restrictions: [
      'Provider type and name remain required. Legacy records may have no contact rows or an incomplete location; they can remain editable without adding a primary email.',
      'The edit wizard does not remove the primary location. Address line 1 is required when changing an address; City is required when an address is supplied.',
      'An existing Stable visit without a radius may remain unchanged. A new or changed radius must be greater than zero; radius only applies to Stable visit.',
      'An Under review provider must use its approval action rather than Activate/Deactivate.',
      'The wizard edits the primary location; manage additional locations on the provider detail page.',
    ],
  },
  {
    id: 'provider-profile-collections',
    title: 'Manage provider contacts, locations, specializations, languages, and qualifications',
    purpose: 'Maintain provider-related collections from the edit wizard or profile detail sections.',
    where: 'Admin portal → Directory Management → Providers → select provider → Edit or detail sections',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Open the provider whose collections need updating.'],
    steps: [
      '1. To change email or phone collections, choose Edit and use Add email / Add phone, the primary selector, or a row’s remove control. Complete or remove each blank row.',
      '2. To change Specializations or Languages, choose Edit, search/select or clear catalog values, and save. Existing inactive relationships can be retained or removed.',
      '3. To add an additional address, open Locations and choose Add location. Enter required Address line 1 and City; optionally add location name, address line 2, state/province, country, postal code, latitude, and longitude. Choose Set as primary location only if it should replace the primary.',
      '4. To change or remove an address, choose Edit or Remove beside it. Review the address before saving; confirm permanent removal in the dialog.',
      '5. For doctors, add or edit qualifications in Qualifications using Title, Institution, Year obtained, and Description. Choose Add qualification or Save changes; confirm before Remove.',
      '6. Review the refreshed profile sections to verify the saved collections.',
    ],
    result: 'Provider contacts, relationships, locations, and doctor qualifications reflect the saved collection changes.',
    restrictions: [
      'Contact rows are optional, but every retained row must contain a valid value. The form supports one primary email and one primary phone.',
      'Additional locations require Address line 1 and City. Removing a location is permanent and requires confirmation.',
      'Qualification Title is required; Institution, Year obtained, and Description are optional.',
      'New selections use active catalog values; an assigned inactive value may be retained or removed in the edit form.',
    ],
  },
  {
    id: 'provider-lifecycle-publication',
    title: 'Change provider status and directory publication',
    purpose: 'Manage operational status separately from whether a provider listing is visible in the directory.',
    where: 'Admin portal → Directory Management → Providers → row Actions or provider profile',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Find the provider and review its Status and Publication state.'],
    steps: [
      '1. Read the current status badge (Under review, Active, or Inactive) and publication badge (Published or Unpublished).',
      '2. For an Active or Inactive provider, choose Deactivate or Activate from Actions or the profile action menu.',
      '3. Separately choose Publish or Unpublish to change directory visibility.',
      '4. If the provider is Under review, choose Approve provider when appropriate and read the approval/email-delivery result.',
      '5. Revisit the record and check both badges to confirm the intended state.',
    ],
    result: 'The provider’s operational status and public listing state are independently updated.',
    restrictions: [
      'Under review records do not show Activate/Deactivate; use Approve provider when appropriate.',
      'Publishing and activation are distinct controls. Do not infer one state from the other.',
      'Email-delivery failure does not roll back an approval.',
    ],
  },
  {
    id: 'provider-portal-access-recovery',
    title: 'Send, recover, or cancel provider portal access',
    purpose: 'Inspect portal-access eligibility and send a setup or reset link to an eligible provider contact.',
    where: 'Admin portal → Directory Management → Providers → select provider → Provider portal access',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Confirm the intended recipient from status and selectable contact email.'],
    steps: [
      '1. Review Status, Recipient, last setup-link issue time, and any explanation. If status fails to load, choose Retry before acting.',
      '2. For eligible or pending setup, choose Contact email for portal access and select the correct listed address. For an eligible linked account, review its recipient and choose Send password reset email when offered.',
      '3. Choose Send password setup email, Resend password setup email, or Send password reset email as presented. Review the result and updated access status.',
      '4. If the provider is Under review, use Approve provider when appropriate and inspect delivery; choose Retry approval email only when offered.',
      '5. If pending access was created for a wrong address, choose Cancel pending access and confirm Cancel access. This invalidates the link; send new access to the corrected contact if eligible.',
      '6. If access is invitation-owned, follow Open invitation workflow and use Invitations.',
    ],
    result: 'A setup/reset email is requested for the selected contact, or pending unactivated access is canceled and its link invalidated.',
    restrictions: [
      'Initial setup can only use emails shown as selectable provider contacts. A reset link goes to the linked login address.',
      'Sending a reset link does not change a password unless the provider uses it. Email handoff does not guarantee inbox delivery.',
      'Cancel pending access permanently removes the unactivated account and invalidates its link; it cannot revoke an activated account.',
      'An invitation-owned flow is managed in Invitations, not through provider access controls.',
    ],
  },
  {
    id: 'provider-doctor-visits',
    title: 'Review and schedule doctor visit periods',
    purpose: 'Review a doctor’s visit availability and manage future return periods and their visit locations.',
    where: 'Admin portal → Directory Management → Providers → select Doctor / Vet → Doctor trips',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Open a Doctor / Vet profile.'],
    steps: [
      '1. Review availability and trip periods, labeled Previous, Current, or Upcoming against the local calendar date.',
      '2. If availability is Visiting, choose Add future return. Enter location name, Address line 1, City, optional state/province, country and postal code, and Start date and End date.',
      '3. Choose Add return. Location, start date, and end date are required.',
      '4. To correct an Upcoming period, choose Amend, revise its location or dates, and choose Save amendment.',
      '5. Review the refreshed Doctor trips list to confirm the saved period.',
    ],
    result: 'A future visit period appears with date range and location, or the upcoming period shows its amended values.',
    restrictions: [
      'Add future return is available only when the doctor is marked Visiting.',
      'The start date cannot be in the past; only Upcoming visits can be amended.',
      'The end date must be on or after the start date.',
      'These are scheduled periods, not appointment slots or a guarantee of immediate availability.',
    ],
  },
  {
    id: 'provider-visiting-calendar',
    title: 'Browse the admin visiting-provider calendar',
    purpose: 'See which visiting providers have a scheduled period covering a selected date and open their admin profile.',
    where: 'Admin portal → Dashboard → Visiting providers → View full calendar',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Scheduled visit periods must exist for a month to show visit cards.'],
    steps: [
      '1. From the dashboard’s Visiting providers card, choose View full calendar.',
      '2. Use Previous month and Next month to browse the schedule, or choose Today to return to the current date.',
      '3. Select a date in the calendar or mobile day list. The agenda shows periods covering that date.',
      '4. Review provider name, specializations, location, and displayed period, then choose Provider profile to open its admin record.',
      '5. If the schedule fails to load, choose Try again. Use the return link to go back.',
    ],
    result: 'The selected date’s scheduled periods are displayed, and a visit card links to its provider profile.',
    restrictions: [
      'The calendar shows scheduled periods, not appointment slots, real-time availability, or a guarantee that a provider can accept a visit. Contact the provider to confirm.',
      'Previous-month navigation is disabled before the current month. A month without periods shows an empty schedule.',
    ],
  },
  {
    id: 'provider-photo-management',
    title: 'Upload and review provider photos',
    purpose: 'Add profile or gallery images, set the profile photo, and remove obsolete images.',
    where: 'Admin portal → Directory Management → Providers → Add/Edit provider or select provider → Photos',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Have permission to use the image files for this provider.'],
    steps: [
      '1. For a new provider, optionally choose a Profile photo in Basic details. On a provider detail page, choose Add photos to open the gallery upload panel.',
      '2. Select or drag in JPEG, PNG, GIF, or WebP images. Each file must be no larger than 10 MB.',
      '3. Review staged previews. Add descriptive Alt text and optional Caption, remove any staged image not wanted, then choose Upload photo or Upload [number] photos.',
      '4. Wait for each result. Successful photos appear in the gallery; a failed file is named in the error so it can be retried.',
      '5. Review the Profile photo badge. On another image, choose Set as profile photo to use it as the listing thumbnail.',
      '6. To remove an existing image, choose Remove and confirm permanent deletion.',
    ],
    result: 'Uploaded photos appear in the provider collection with metadata, and the chosen thumbnail is marked Profile photo.',
    restrictions: [
      'Only JPEG, PNG, GIF, and WebP files up to 10 MB each are accepted.',
      'Detail-page photos are staged and uploaded only after Upload is chosen. Alt text is recommended; captions are optional.',
      'Removal is permanent and requires confirmation. If initial creation succeeds but photo upload fails, retry or edit the saved provider rather than creating a duplicate.',
    ],
  },
  {
    id: 'provider-applications',
    title: 'Review provider applications',
    purpose: 'Inspect provider registrations and decide whether to approve or reject an application.',
    where: 'Admin portal → Directory Management → Provider applications → New applications',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Review status and email-verification state before deciding.'],
    steps: [
      '1. Open New applications. Search by provider, contact, or email; use Filters for provider type, email verification, and review status.',
      '2. Open Actions → View application. Review provider/professional details, specializations and languages, applicant contacts, working address, services, consent, verification and review state, submission/review details, and rejection reason if present.',
      '3. Confirm the application is Pending review. Choose Approve & stage listing or Reject.',
      '4. Read the confirmation: approval creates one draft, unpublished listing; rejection prevents provider access and listing creation. Confirm the decision.',
      '5. Review the updated state. Manage an approved staged listing separately in Providers.',
      '6. Choose Updates to review profile changes submitted by existing providers.',
    ],
    result: 'The decision is recorded. Approval stages one draft, unpublished provider listing; publication and provider management remain separate.',
    restrictions: [
      'An Awaiting email verification application is not a verified pending application.',
      'Only Pending review applications expose decision actions; reviewed applications are view-only.',
      'Application approval does not publish the resulting listing.',
    ],
  },
  {
    id: 'provider-profile-updates',
    title: 'Review provider profile updates and photos',
    purpose: 'Compare proposed changes with the approved profile before accepting or rejecting them.',
    where: 'Admin portal → Directory Management → Provider applications → Updates',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'An existing provider must have submitted a profile update.'],
    steps: [
      '1. Open Provider applications → Updates. Search by provider or filter by Pending review, Approved, or Rejected.',
      '2. Open Actions → Compare profiles. Review provider, submission time, and any previous rejection reason.',
      '3. Compare current and proposed name, description, email/phone, website, visit availability/radius, emergency services/contact, specializations, locations, contact collections, professional fields, qualifications, and visit additions.',
      '4. Review Photo comparison for Current photos and Proposed photos, including Added, Removed, Unchanged, metadata/order, and profile-photo changes. If an image is unavailable, use its status and metadata rather than assuming it is unchanged.',
      '5. For Pending review, choose Approve update or Reject update. Rejection may include optional Feedback for the provider (up to 500 characters); confirm.',
      '6. Review updated status. Use the provider detail page or Activity Logs to inspect separately managed account state.',
    ],
    result: 'The submitted update is applied, or rejected while the approved profile remains unchanged.',
    restrictions: [
      'Only Pending review updates expose decision actions.',
      'An update decision changes only the submitted profile update; it does not change active status, publication, or account state.',
      'Proposed visit additions are appended and do not replace scheduled or completed visits.',
      'Photo comparison uses stored photo identity and metadata; it is not a separate photo approval control.',
    ],
  },
  {
    id: 'provider-invitations',
    title: 'Create and manage provider invitations',
    purpose: 'Invite a provider to complete onboarding and track delivery, acceptance, completion, or cancellation.',
    where: 'Admin portal → Directory Management → Invitations',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Confirm provider type, name/contact name, and recipient email.'],
    steps: [
      '1. Choose New Invitation and select Hospital, Clinic, or Doctor. For Doctor enter First name and Last name; for Hospital or Clinic enter Provider name.',
      '2. Enter valid Recipient email and choose Send invitation. If saved but delivery fails, close the notice and use Resend on the saved row.',
      '3. Search by recipient/provider; filter by invitation Status, Provider type, and Sent from/to dates. Use pagination.',
      '4. Choose Actions → View to inspect type, provider, status, sent/expiry times, and accepted, completed, or portal-access timestamp when present.',
      '5. For Pending or Expired, choose Resend. For Pending, choose Cancel and confirm to invalidate it. Choose Copy Link only while a link is available from a recent create/resend in this session.',
      '6. For Completed, choose View submitted details. Use its password setup action only when the invitation has no portal account; linked accounts use provider access controls.',
    ],
    result: 'The invitation list reflects onboarding status and supported resend, cancellation, link-copy, or setup actions.',
    restrictions: [
      'Invitation states are Pending, Accepted, Expired, Cancelled, or Completed; available actions depend on state.',
      'Raw links are available only in the current page session after creation or resend. If unavailable, use Resend for a fresh link.',
      'Cancel invalidates the invitation. A delivery failure may occur after it is saved; verify the row and use Resend rather than creating a duplicate.',
      'Doctor invitations require first and last names; combined name must be at most 300 characters. Recipient email must be valid and not already in use.',
    ],
  },
  {
    id: 'specializations-catalog',
    title: 'Manage and import specializations',
    purpose: 'Maintain the specialization catalog used in provider profiles.',
    where: 'Admin portal → Directory Management → Specializations',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'For CSV import, prepare UTF-8 CSV using the downloaded template.'],
    steps: [
      '1. Search by specialization name, filter Active or Inactive, and use pagination.',
      '2. Choose Add specialization to enter required Name, optional Description, and initial Active setting. Choose Edit to update Name or Description and Save changes.',
      '3. Use Deactivate or Activate to control availability for new selections.',
      '4. Choose Export for the current filtered catalog. Choose Import and Download Template to prepare a CSV.',
      '5. In the import dialog, choose or drag a .csv file up to 5 MB. Required columns are Name, Description, and Status (ACTIVE or INACTIVE). Review total, valid, duplicate, invalid rows and row reasons.',
      '6. If no rows are valid, correct the file. Otherwise choose Import [number] specializations and review imported, skipped, and error counts.',
      '7. If offered, download the error report to inspect non-valid rows. Choose Done and confirm the refreshed catalog.',
    ],
    result: 'Catalog values can be created, edited, activated/deactivated, exported, or imported with preview and result.',
    restrictions: [
      'Name is required and limited to 200 characters; optional Description is limited to 2,000 characters.',
      'CSV accepts .csv files up to 5 MB. Duplicates and invalid rows are identified; only valid rows can be imported.',
      'Only active specializations are offered for new provider selections. Existing inactive assignments can be retained or removed during edits.',
    ],
  },
  {
    id: 'languages-catalog',
    title: 'Manage the language catalog',
    purpose: 'Maintain language names and codes used in provider profiles.',
    where: 'Admin portal → Directory Management → Languages',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Search by language name or code, filter Active or Inactive, and use pagination.',
      '2. Choose Add language, enter Language name and Language code, and save.',
      '3. Choose Edit to revise a value and Save changes.',
      '4. Use Deactivate or Reactivate to control availability for new selections.',
      '5. For an active language no longer needed in active selections, choose Delete and confirm Deactivate language.',
      '6. Review the refreshed status in the table.',
    ],
    result: 'The language name/code is saved and its current selection state appears in the catalog.',
    restrictions: [
      'Language name and code are required. Codes accept 2–10 letters with an optional hyphen and 2–10-letter subcode, such as en or pt-BR.',
      'Delete is offered only for active rows and removes the value from active language selections.',
      'The Languages page has no CSV import/export workflow.',
    ],
  },
  {
    id: 'provider-reviews-moderation',
    title: 'Moderate provider reviews',
    purpose: 'Review a member’s rating/comment, decide publication status, and retain moderation notes and history.',
    where: 'Admin portal → Directory Management → Reviews',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'A member review must exist.'],
    steps: [
      '1. Filter by All reviews, Pending, Published, Rejected, or Hidden. If scoped from a provider review count, choose View all reviews to clear scope.',
      '2. Review provider, member name/email, rating, status, and submission time; choose View to load details.',
      '3. Read the comment and timestamps, then inspect Moderation history and retained snapshots.',
      '4. For Pending, choose Approve & publish. Choose Reject to reject; for Published choose Hide comment; for Hidden choose Restore comment.',
      '5. Optionally enter or revise Member-visible moderation note and Internal administrator note. Choose Save notes when no status decision is required.',
      '6. If a concurrent change is reported, wait for the latest review version and history to refresh, review the new state, then decide again if appropriate.',
    ],
    result: 'Review status and allowed notes are saved, with actions and retained before/after content shown in moderation history.',
    restrictions: [
      'Owner-deleted reviews are read-only for administration; notes and moderation actions are disabled.',
      'Hidden is only available for Published or already Hidden reviews. A stale version must be refreshed before another update.',
      'Member-visible notes are limited to 2,000 characters; internal notes to 4,000 characters.',
    ],
  },
  {
    id: 'admin-subscribers',
    title: 'Search and export subscribers',
    purpose: 'Find launch-registration subscribers and export matching records as CSV.',
    where: 'Admin portal → Enquiries → Subscribers',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Search by email address.',
      '2. Open Filters and choose Registration type (Vet, Horse Owner, Hospital, Clinic, Stable Manager, or Other) and/or Submitted from/to dates.',
      '3. Choose Export CSV to export records matching current search, type, and date filters. Read the displayed error if export cannot be prepared.',
      '4. Review Email address, Register as, and Submitted fields; use pagination to browse results.',
      '5. Adjust or clear search and filters to change result or export scope.',
    ],
    result: 'The table and CSV export are scoped to the applied search, registration type, and submission dates.',
    restrictions: [
      'Subscribers are launch-interest registrations, not signed-in member accounts.',
      'Check search and date range before export; it uses current filters.',
      'Submitted from cannot be after Submitted to.',
    ],
  },
  {
    id: 'admin-contact-enquiries',
    title: 'Review contact enquiries',
    purpose: 'Find and read a message submitted through the public contact form.',
    where: 'Admin portal → Enquiries → Contact Enquiries',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Search by name, email, phone, or message.',
      '2. Open Filters to narrow by enquiry type (General enquiry, Listing my practice, Partnership, or Other) and Submitted from/to date.',
      '3. Choose Clear dates or Clear all filters as needed. Correct an invalid date range before expecting matches.',
      '4. Review sender, email, type, phone, and submission time; choose View.',
      '5. Read Full name, email, enquiry type, phone, submitted time, and complete Message. Use the breadcrumb or Back to contact enquiries to return with filters preserved.',
    ],
    result: 'The selected contact message is available with submitted sender/contact information and complete message text.',
    restrictions: [
      'The page is read-only; it does not reply to, assign, edit, or delete an enquiry.',
      'Treat contact details and message as private. Phone may be absent.',
      'Submitted from must be on or before Submitted to.',
    ],
  },
  {
    id: 'admin-platform-feedback',
    title: 'Process private platform feedback',
    purpose: 'Read member feedback, record its processing state, and separate member-visible responses from internal notes.',
    where: 'Admin portal → Enquiries → Platform feedback',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'A member feedback submission must exist.'],
    steps: [
      '1. Search by member, email, subject, or message. Filter by Feedback status or category; use Clear filters to reset.',
      '2. Review member, category, subject/rating, status, and submitted/updated times. Choose View to open the full feedback.',
      '3. Read the feedback and inspect Action history, including retained submission/moderation snapshot.',
      '4. For a record not withdrawn, enter an optional Member-visible response and/or Internal administrator note. Set status to Pending, In review, Resolved, or Rejected.',
      '5. Choose Save processing update. If a concurrent change/version error appears, review refreshed values before making another update.',
      '6. Choose Back to platform feedback to return with list filters.',
    ],
    result: 'Status, member response, and administrator-only note are saved and recorded in action history.',
    restrictions: [
      'Withdrawn feedback is read-only: retained content/history remain visible, but processing fields cannot be changed.',
      'Keep public response and internal note separate; do not put private operational notes in the member response.',
      'Writes use a version check. If another administrator changed the record, the latest version is refreshed instead of blindly overwritten.',
      'Feedback details contain private member information; use only for authorized support and processing.',
    ],
  },
  {
    id: 'admin-activity-logs',
    title: 'Inspect activity logs',
    purpose: 'Review the history of meaningful administrator and invitation activity and its recorded field changes.',
    where: 'Admin portal → Profile menu → Activity Logs',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Open Activity Logs from the profile menu.',
      '2. Set From date and/or To date to filter the period. Choose Clear dates to remove the range.',
      '3. Review When, Actor name/email, Activity action, and summary.',
      '4. Where Details lists changed fields, expand the row to compare before and after values.',
      '5. Use pagination for more rows. If loading fails, choose Retry.',
    ],
    result: 'Activity for the selected period is available with actor, summary, and recorded field-value changes.',
    restrictions: [
      'Activity Logs is an audit view; it has no controls to edit or replay an action.',
      'Not every action records field values. “No field values recorded” does not mean the action failed.',
      'This page filters by date and pagination, not general text search.',
    ],
  },
  {
    id: 'admin-email-logs',
    title: 'Review email delivery logs',
    purpose: 'Read transactional email handoff attempts, purposes, delivery statuses, and recorded failure details.',
    where: 'Admin portal → Profile menu → Email Logs',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.'],
    steps: [
      '1. Open Email Logs and review Sent, To, For, and Status for each recorded attempt.',
      '2. Choose Date filter: All dates, Specific day, Month, Year, or Custom range.',
      '3. Enter the required date value(s). Incomplete filters are not applied; choose Clear filter to show all attempts.',
      '4. Interpret Accepted by SMTP as a recorded handoff, Outcome pending as unresolved, and Failed together with its failure message.',
      '5. Use pagination to review older attempts.',
    ],
    result: 'The selected period shows read-only email-attempt history with recipient, purpose, status, and any recorded failure detail.',
    restrictions: [
      'Email Logs is read-only; it does not send or retry messages.',
      'Accepted by SMTP confirms handoff, not inbox delivery. An Outcome pending status does not confirm delivery.',
      'Use the originating workflow or support process to investigate or retry a notification; do not infer success from a missing log row.',
    ],
  },
  {
    id: 'admin-settings',
    title: 'Configure admin date and time display',
    purpose: 'Set the system-wide timezone, date format, and clock format used across the portal.',
    where: 'Admin portal → Profile menu → Settings',
    who: 'Administrators',
    prerequisites: ['Sign in with an admin-role account.', 'Wait for current settings to load before editing.'],
    steps: [
      '1. Open Settings and wait for saved settings to load. If loading fails, read the error; already-loaded portal values may be used as a fallback.',
      '2. Choose a Timezone from the available IANA timezone list.',
      '3. Choose a Date format (MM/DD/YYYY, DD/MM/YYYY, or YYYY/MM/DD) and Time format (12-hour or 24-hour).',
      '4. Review the live Date, Time, Weekday, and Full timestamp preview.',
      '5. Choose Save settings and wait for “Settings saved”; the shared portal time-settings context refreshes.',
      '6. To discard unsaved changes, choose Reset to restore current live settings.',
    ],
    result: 'The portal displays timestamps using the saved timezone and date/time formats.',
    restrictions: [
      'These are system-wide display preferences; they do not change record timestamps or a provider/member location.',
      'Reset restores current live values, not an arbitrary factory default. A failed save is reported and leaves changes unsaved.',
    ],
  },
];