import type { ManualTopic } from './types';

export const analyticsTopics: ManualTopic[] = [
  {
    id: 'analytics-workspace-and-date-controls',
    title: 'Open Analytics and choose a reporting period',
    purpose: 'Use the administrator Analytics workspace to choose which report to read and the system-timezone dates represented by its period metrics.',
    where: 'Open /admin/analytics. The Dashboard page also has the link “View detailed analytics →”; that link opens this separate reporting workspace.',
    who: 'Administrators with the admin role. The analytics API checks for this role; provider and member portal users do not have access.',
    prerequisites: ['Sign in to the administrator portal. To interpret business reports, remember that their numbers come from retained records and their available history varies by source.'],
    steps: [
      '1. Open Analytics. The initial section is Overview and the default range is Last 30 days.',
      '2. Select one of the six section tabs: Overview, Website traffic, Members, Providers, Reviews & feedback, or Enquiries & subscribers. Overview links to the five detailed sections; the selected section and date controls are reflected in the page URL.',
      '3. Use Date range to choose Today, Yesterday, Last 7 days, Last 30 days, This month, Last month, All available data, or Custom range. For Custom range, enter both From and Through dates. The start must be on or before the end; dates cannot be in the future and the range cannot exceed ten years.',
      '4. Use Group by to choose Daily, Weekly, or Monthly buckets for time-series reports. This changes how events in the same period are grouped; it does not change the selected date boundaries.',
      '5. Read the displayed date span and timezone below the controls. All report dates are calendar dates in that configured system timezone, even if your computer uses another timezone.',
      '6. Select ↻ Refresh when you need to reload the current reports. Wait for the refresh to finish; if a report panel fails, use its Retry reports action, or the retry shown for a failed summary.',
    ],
    result: 'Analytics displays the selected section for the chosen inclusive calendar-date range, with its applicable summary, trend and detail reports. The Overview section presents only Website page views, Provider profile views, New member registrations, New provider applications, Accepted enquiries and New unique subscribers when those source metrics are supplied; use a detailed section for additional measures.',
    restrictions: [
      'Custom ranges need both dates and valid ordering. While a custom range is incomplete or reversed, the page does not request reports; correct the dates before interpreting results.',
      'A date range is not proof that every data source has complete history for those dates. Review coverage and availability before comparing or treating a displayed zero as complete activity.',
      'The operational Dashboard is a separate page. Its provider counters, invitation/registration cards, visitor chart and location map are not the Analytics sections or their date-filtered reports.',
      'No non-administrator role boundary is expanded by the links from Dashboard or Analytics.',
    ],
  },
  {
    id: 'analytics-website-traffic',
    title: 'Read website traffic and discovery reports',
    purpose: 'Interpret route-view activity, estimated visitor-days and provider discovery without confusing separate measures or uncovered dates with zero activity.',
    where: 'Analytics → Website traffic. The detailed section is /admin/analytics?section=traffic.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Open Analytics and select Website traffic. Traffic reporting is prospective from its recorded instrumentation start date; older traffic history is unavailable.'],
    steps: [
      '1. Select Website traffic. Its headline cards are Website page views, Directory views and Provider profile views. Use Trend metric to switch the single time-series chart among the available traffic metrics, including estimated visitor-days and the separate Legacy homepage visits measure.',
      '2. Read Website page views as successful views of allowlisted routes. Directory and profile views are successful verified-member pages; profile views refer only to providers who were discoverable when viewed.',
      '3. Interpret Estimated visitor-days as the sum of browser-deduplicated daily estimates, not unique people across the whole selected period. Latest daily visitor estimate is a current daily estimate, not a period total.',
      '4. Use Page views by public page category to inspect the category breakdown. Open View data table below a chart to replace its graphic with labeled values; close it to return to the chart.',
      '5. Use Provider popularity on this tab to inspect provider-linked profile activity. Search providers or use the Provider type filter (Doctor, Clinic or Hospital) when you want the corresponding provider population or profile views; these do not narrow sitewide page views.',
      '6. Expand Definitions & source coverage to check the tracking-start date and whether the chosen period is partial or unavailable. Expand a chart’s How this is counted disclosure when its counting definition is needed.',
    ],
    result: 'The section shows traffic counts and categories for covered dates, identifies available provider profile ranking data, and communicates when part of the selected interval predates tracking.',
    restrictions: [
      'Dates before traffic instrumentation are unavailable, not zero. A range that overlaps rollout is partial; its trend begins with the first covered date.',
      'A visitor estimate is browser-deduplicated, not a verified-person count. Different devices or storage resets may overcount; unavailable browser storage may undercount. Multi-day sums must remain labeled visitor-days.',
      'Legacy homepage visits are the independent existing homepage-only counter; do not add them to new sitewide route views or call them unique visitors.',
      'Provider filters can scope provider-linked profile measures or provider ranking; they do not narrow sitewide route views, page categories or visitor estimates. Member geography is not visitor geography.',
      'Analytics stores aggregates rather than member identities or browsing histories. Do not infer an individual visitor from these reports.',
    ],
  },
  {
    id: 'analytics-member-registration-cohorts',
    title: 'Review member registrations and cohort state',
    purpose: 'Count new public member accounts in a selected period and understand the current state of that same registration cohort.',
    where: 'Analytics → Members. The section route is /admin/analytics?section=registrations; use the “Open registered users →” link for account administration.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Choose the reporting dates first. Registration cohort verification and account activity are current states, not historical states as of each signup date.'],
    steps: [
      '1. Select Members and read New member registrations for the selected period. This counts newly created public horse-owner and stable-manager accounts once per account.',
      '2. Read Verified in selected cohort as the current email-verification state of accounts created in the selected period, not as a count of verification events that happened during those dates.',
      '3. Use More filters to choose Member role (Horse owner, Stable manager, or Both), Verification (Verified or Unverified), and Account (Active or Inactive). These filter the registration cohort reports.',
      '4. Use the Member cohort by exclusive role chart and its View data table to compare the selected cohort’s exclusive role groups. “Both” is one exclusive group for accounts with both public roles.',
      '5. Open View detailed reports for source-aligned cohort details, including the cohort’s current account state and role-assignment counts. Role assignments may overlap: one dual-role account contributes to both assignment counts while remaining one account in the total.',
      '6. Expand Definitions & source coverage when you need the observed first/last registration dates or the report’s explanation of selected-period events versus present-day state.',
      '7. Select “Open registered users →” when you need the underlying user-management page rather than an aggregate analytics count.',
    ],
    result: 'The selected-period registration total and its current verification, activity and role breakdowns are shown separately, with a link to the registered-users administration area.',
    restrictions: [
      'Member filters apply to registration cohorts only; they do not narrow traffic, providers, enquiries or subscribers.',
      'The count excludes administrator and provider accounts and counts a dual-role member once. Do not add overlapping role-assignment values to derive unique accounts.',
      'Verified and active values describe the cohort’s current state when reported. They do not reconstruct each account’s historical state at signup.',
      'Analytics is an aggregate report, not the underlying member list. Follow the registered-users link only if you are authorized to administer those records.',
    ],
  },
  {
    id: 'analytics-provider-inventory-applications-invitations',
    title: 'Review provider inventory, applications and invitations',
    purpose: 'Distinguish the current provider catalogue from period applications and invitations, then inspect the provider popularity table when needed.',
    where: 'Analytics → Providers. The detailed section is /admin/analytics?section=providers. Management links lead to /admin/providers, /admin/provider-applications and /admin/invitations.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Choose the reporting window before comparing period event counts. Current inventory and status breakdowns are live snapshots.'],
    steps: [
      '1. Select Providers. The headline report includes New provider applications, Invitations created, Invitations sent, and Current listed providers when supplied. Current listed providers counts the provider catalogue, including unpublished and inactive records; it is not a count of period additions.',
      '2. Use More filters for Provider type (Doctor, Clinic or Hospital), Provider status (Draft, Under review, Active or Inactive), Publication (Published or Unpublished), Listing country and Listing city. Application status (Awaiting verification, Pending review, Approved or Rejected) and Invitation status (Pending, Accepted, Completed, Cancelled or Expired) narrow their matching reports.',
      '3. Read Provider applications as application records created in the date range. Application decisions are counted by the recorded reviewed_at time, so an application submitted earlier may have its approval or rejection decision in the selected period.',
      '4. Read Invitations created by their creation date and Invitations sent by their persisted sent timestamp. Open View detailed reports for the selected-period cohorts’ current status and the all-current-status snapshots.',
      '5. Interpret invitation compatibility totals carefully: accepted combines ACCEPTED and COMPLETED; cancelled-or-expired combines CANCELLED and EXPIRED. A cancelled or expired invitation is not evidence that its recipient rejected it.',
      '6. Open View detailed reports to load current provider inventory and see inventory by status, type and publication. Active means current ACTIVE status; active and publicly discoverable means both ACTIVE and PUBLISHED.',
      '7. Use Provider popularity to search one provider name, sort Provider, Period profile views, Period review submissions or Current average, and page through the server results. Additional sort options are Eligible rating count and Current saves. Use Show entries to select 10, 25 or 100 rows per page. The visible measures distinguish period activity from current ratings and saves.',
      '8. Open Provider details within a row for listing type/status, publication, eligible ratings and current saves. Select a provider name to open its provider record, or View reviews to open review moderation filtered to that provider.',
      '9. Use the page links “Open provider directory →”, “Review applications →” or “Manage invitations →” to perform the corresponding record-management work.',
    ],
    result: 'The selected reports separate current catalogue inventory from selected-period application/invitation activity, while the sortable provider table presents period popularity alongside current rating and save snapshots.',
    restrictions: [
      'Provider status and publication describe present-day inventory; analytics does not reconstruct historical inventory or publication states.',
      'Provider type can apply across provider, application and invitation reports. Listing geography and provider lifecycle status do not automatically narrow application or invitation records; each filter applies only where the underlying records have that relationship.',
      'Application status filters applications; invitation status filters invitations. Do not interpret a submitted cohort’s current state as an event count for that state change.',
      'Provider popularity rows include matching zero-activity catalogue records. Before tracking begins, profile views are unavailable rather than zero.',
      'Only administrators should use the record-management links. Analytics does not expose recipient contact details or invitation tokens.',
    ],
  },
  {
    id: 'analytics-reviews-and-private-feedback',
    title: 'Read provider-review and private-feedback reports',
    purpose: 'Keep provider-review moderation and rating statistics distinct from private platform feedback, and inspect only aggregate data here.',
    where: 'Analytics → Reviews & feedback. The detailed section is /admin/analytics?section=reviews; management links lead to /admin/reviews and /admin/feedback.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Select a date range. Review submissions and feedback submissions are period events; eligible ratings and current backlogs are snapshots.'],
    steps: [
      '1. Select Reviews & feedback. The headline cards distinguish Review submissions, Private feedback submissions, Current eligible average rating with its eligible count, and Average platform feedback rating with its rated-response count.',
      '2. Use More filters to narrow provider-linked review reports by Provider type (Doctor, Clinic or Hospital), Provider status (Draft, Under review, Active or Inactive), Publication (Published or Unpublished), provider name, Review moderation (Pending, Published, Hidden or Rejected), or Star rating (1–5). Use Feedback category (Website / App, Search & Matching, Provider Experience, Account / Profile, Technical Issue, Suggestion or Other) and Feedback state (Pending, In review, Resolved, Rejected or Withdrawn) to scope private feedback.',
      '3. Read Review submissions as original review records created in the period. Editing a review or moderating it later is not a new submission; View detailed reports separately lists period review actions.',
      '4. Interpret current eligible provider ratings as undeleted PUBLISHED or HIDDEN reviews. Hidden approved reviews remain eligible; pending, rejected and deleted reviews do not contribute. Deleted history is shown separately from active moderation states.',
      '5. Use Eligible ratings by star and its View data table for the current eligible rating distribution. Compare the average only together with its eligible count.',
      '6. Use Private feedback submissions by category for category totals, not message content. The detailed reports distinguish current non-withdrawn backlog state, the selected-period cohort’s current state, withdrawn records and optional rating aggregates.',
      '7. Expand Definitions & source coverage to check which observations are retained and why current snapshots do not represent past states. The page links “Open review moderation →” and “Open private feedback management →” lead to their respective admin workflows.',
    ],
    result: 'Provider-review submissions, moderation history and eligible provider ratings remain distinct from private platform feedback, with category/status/rating totals and separate withdrawn or deleted counts where reported.',
    restrictions: [
      'Provider filters scope provider-linked reviews and ratings, not private platform feedback. Feedback category/status filters scope feedback; they do not change provider reviews.',
      'Feedback is private. Analytics exposes aggregate counts and optional rating aggregates only; do not expect or export submitter names, addresses, message text or internal notes.',
      'Review submission counts use original creation time and include retained submitted records even if later deleted; active states and eligible ratings exclude deleted records.',
      'The headline platform-feedback average and response count are current snapshots; feedback detail ratings are scoped to the selected period. Check each label and basis before comparison.',
      'Pending/rejected reviews are not eligible public ratings. Do not combine feedback ratings with provider-review ratings.',
    ],
  },
  {
    id: 'analytics-enquiries-and-subscribers',
    title: 'Review enquiries and subscriber activity',
    purpose: 'Compare durably stored enquiries and unique subscriber records by date and stored category without treating repeated attempts or email delivery as records.',
    where: 'Analytics → Enquiries & subscribers. The detailed section is /admin/analytics?section=engagement; management links lead to /admin/contact-enquiries and /admin/subscribers.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Set the desired date range. The report counts records accepted and stored by the portal.'],
    steps: [
      '1. Select Enquiries & subscribers and read Accepted enquiries and New unique subscribers for the selected period.',
      '2. Use More filters to select an Enquiry type (General, Listing, Partnership or Other) or Subscriber type (Vet, Horse owner, Hospital, Clinic, Stable manager or Other). Each filter scopes only its matching dataset.',
      '3. Use Accepted enquiries by type and Unique stored subscribers by type to compare stored category counts. Open View data table below either chart for its labeled values.',
      '4. Read accepted enquiries as durably stored records, independent of whether a notification email was delivered. Read subscribers as newly inserted unique stored subscription records, not every repeated form submission attempt.',
      '5. Open View detailed reports to inspect source-aligned breakdowns and definitions. Expand Definitions & source coverage if you need retained-date observations or event-versus-snapshot guidance.',
      '6. Use “Open enquiries →” or “Open subscribers →” when you need the separate record-management workflow.',
    ],
    result: 'The selected-period enquiry and subscriber measures, trends and type breakdowns are displayed as aggregate counts, with direct links to the appropriate administrator management pages.',
    restrictions: [
      'Enquiry type affects enquiries only; Subscriber type affects subscribers only. Provider and member filters do not narrow these datasets.',
      'An enquiry total does not prove email delivery or resolution. No resolution state is inferred by the analytics report.',
      'Repeated signup attempts for an already stored email do not count as another newly stored subscriber.',
      'Analytics does not display or export contact details, subscriber email addresses, enquiry messages or personal notes.',
    ],
  },
  {
    id: 'analytics-trends-detail-tables-and-coverage',
    title: 'Inspect trends, definitions, detail tables and coverage',
    purpose: 'Use the report’s charts and expandable tables to verify what a metric counts, what is included in each aggregate and whether a comparison is supported.',
    where: 'On any Analytics section, use Trend metric, chart disclosures, View data table, View detailed reports, and Definitions & source coverage.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Load an Analytics section and choose the intended range and grouping. Available charts depend on the selected section, returned data and source coverage.'],
    steps: [
      '1. In a detailed section, choose one option in Trend metric. The page shows one selected time series at a time; the options vary by section. The Overview shows its website-page-views trend and links to the detailed sections.',
      '2. Read the trend buckets using the displayed Daily, Weekly or Monthly grouping. Covered zero-activity buckets can be zero; a null/unavailable value or a missing pre-rollout traffic span is not a zero.',
      '3. Use a chart’s How this is counted disclosure for its definition. Select View data table to replace that chart with an accessible Period / category and measure table; select the disclosure again to return to the chart.',
      '4. Open View detailed reports for additional source-aligned aggregate groups. Each group starts closed; expand its heading to read its definition and table of Category / status, Count or Value, and Basis.',
      '5. Read the Basis column and group labels before comparing rows. “Selected period” means events in the selected dates; “current snapshot” means present-day state; selected-period cohorts may be grouped by their current state.',
      '6. Expand Definitions & source coverage. Review the reporting timezone, tracking-start information, availability and source first/last retained observations. Those first/last business-event dates describe observed records, not guaranteed history.',
      '7. Interpret period comparisons only where available. The previous interval has the same number of system-local calendar days as the selected range. A zero prior baseline or unknown/inadequate coverage means a percentage is unavailable, not zero growth.',
      '8. Use the on-screen retry message if an individual report panel fails. A covered zero is a valid result; a failed panel, unavailable source or incomplete custom range has a separate message.',
    ],
    result: 'You can inspect both the visual chart and the exact source-aligned aggregate values, while retaining the distinctions among event dates, current-state snapshots, covered zeroes and unavailable history.',
    restrictions: [
      'Do not infer a conversion funnel: these breakdowns are aggregates and are not linked person-level journeys.',
      'Business-event first/last dates are not independently established coverage bounds. Previous-period comparisons for sources without a known complete-coverage boundary may be unavailable even when older records exist.',
      'Current provider inventory, ratings/saves and moderation states are not historical snapshots. Do not describe them as period changes.',
      'A chart’s table is a text alternative for that same aggregate, not a record-level export or a different population.',
      'Never infer unique people by summing visitor estimates across days; label sums as visitor-days.',
    ],
  },
  {
    id: 'analytics-csv-exports',
    title: 'Export an Analytics report to CSV',
    purpose: 'Download a bounded aggregate CSV for the currently selected report, date range, applicable filters and grouping.',
    where: 'Analytics control deck → Export CSV. Available choices follow the current section; Provider ranking is enabled only for Website traffic and Providers.',
    who: 'Administrators with the admin role.',
    prerequisites: ['Select the intended section and period, complete any custom dates, and apply only the filters relevant to the dataset. Confirm the active section and filters before exporting.'],
    steps: [
      '1. Open Export CSV in the Analytics control deck. Wait until a prior export finishes if the menu is preparing a download.',
      '2. Choose a Time series · metric option to export that selected-section metric, or choose Breakdown · section to export that section’s aggregate breakdown groups. The list reflects the currently selected tab.',
      '3. Choose Provider ranking when working in Website traffic or Providers if you need the filtered and sorted ranking dataset, rather than only the rows visible on the current table page.',
      '4. Wait for the download and read the status: CSV downloaded confirms success. If the request fails, the displayed error indicates it did not succeed; correct the selection if needed and retry.',
      '5. Open the CSV and check its prefixed metadata rows for timezone, date bounds, grouping, applied filters, definitions and source coverage before using the data.',
      '6. Read the column headings below that information. A time-series file pairs each date or date group with its count; a breakdown file pairs report categories with measures; a provider-ranking file includes provider names, listing states, period activity, and current ratings and saves.',
      '7. If the CSV includes the explicit “Export limited to 5,000 rows” notice, treat it as a truncated export. Narrow the report selection before using it as a complete dataset.',
    ],
    result: 'A UTF-8 CSV is downloaded for the selected aggregate dataset with applied scope and interpretation metadata, or a retryable error is displayed if export fails.',
    restrictions: [
      'Each export is capped at 5,000 data rows. A notice row marks truncation; the limit is not evidence that the full result had only 5,000 rows.',
      'Provider-ranking CSV uses the selected backend sort and filters, but includes the matching dataset rather than only the visible page.',
      'CSV values are escaped to reduce spreadsheet formula injection. Keep the leading apostrophe applied to formula-like text when handling exported provider names.',
      'Exports contain aggregate/reporting and non-PII listing fields only. They exclude contact details, private feedback text, internal notes, raw URLs, visitor identifiers and member browsing histories.',
      'A breakdown export is a flattened aggregate report, not a dump of underlying records. Time-series and ranking exports are also bounded and should retain their metadata when shared.',
    ],
  },
  {
    id: 'admin-dashboard-overview-and-activity',
    title: 'Read the Dashboard inventory and activity cards',
    purpose: 'Use the operational Dashboard for current provider counts and all-time invitation/member summaries, plus the separate seven-day homepage-visits chart.',
    where: 'Open /admin/dashboard from the Dashboard item in Admin navigation.',
    who: 'Administrators signed in to the admin portal. The Dashboard route and its statistics API require the admin role.',
    prerequisites: ['Open Dashboard and wait for its statistics to load. These cards are not date-filtered Analytics reports.'],
    steps: [
      '1. In Provider Inventory, read Active providers as the current number of provider records whose status is ACTIVE. This count does not require the provider to be published.',
      '2. Read Hospitals, Clinics and Doctors as the current catalogue totals of each provider type. They include records in any provider status or publication state, so these type totals are not the same population as Active providers.',
      '3. In Activity overview, read Invitation activity across all time. The “Invitations sent” bar is the sum of every stored invitation status (Pending, Accepted, Completed, Cancelled and Expired); it is not a count restricted to email-sent timestamps.',
      '4. Read Accepted as Accepted plus Completed invitations. The Dashboard’s “Rejected” bar is specifically Cancelled plus Expired invitations, as its detail label “Cancelled or expired” explains; Pending invitations appear only in the all-invitations total.',
      '5. Read Member registrations as all public horse-owner and stable-manager accounts, with current Verified and Unverified counts and separate Horse owners and Stable managers role counts. A dual-role member is one registration but contributes to both role counts. The card notes “Email verification unlocks member access.”',
      '6. Read Website visits as the sum for the seven displayed system-timezone calendar dates: today and the prior six days. Missing daily homepage-counter rows display as zero; the individual bars are the daily counts. This is the legacy public landing-page counter, separate from Analytics sitewide route views.',
      '7. Select “Visiting providers” → “View full calendar” to open the separate scheduled-visits calendar. Select “View detailed analytics →” in the page header to open the date- and filter-aware Analytics workspace.',
      '8. If the Dashboard cannot load its statistics, select “Try again”; do not interpret a loading or error state as zero activity.',
    ],
    result: 'You can distinguish the Dashboard’s current provider inventory and all-time status summaries from its seven-day homepage counter and the separate Analytics reports.',
    restrictions: [
      'Provider type totals include inactive, under-review, draft, unpublished and published records. Active providers is a separate current-status count and is not an active-and-published count.',
      'The invitation summary describes the current stored status groups across all time. The visible “Rejected” label is a legacy-compatible grouping for cancellations and expirations, not recipient rejection or email delivery failure.',
      'Member counts include users with a public horse-owner or stable-manager role, not administrator or provider-only accounts. Inactive public accounts are not excluded. Role totals overlap for dual-role accounts; verification is their current state, not signup-period history.',
      'The Dashboard activity cards have no date selector. Use Analytics for selected date windows, definitions, coverage and additional aggregate reports.',
      'Website visits come from the separate public landing-page daily counter. They are not all sitewide route views or verified unique people; browser storage/device differences can affect repeat counting.',
    ],
  },
  {
    id: 'admin-dashboard-provider-locations-map',
    title: 'Inspect provider locations on the Dashboard map',
    purpose: 'Understand which stored provider locations appear on the map, filter the visible markers by type and read the marker popup.',
    where: 'Open /admin/dashboard and scroll to Provider Locations.',
    who: 'Administrators signed in to the admin portal.',
    prerequisites: ['Wait for Dashboard statistics to load. Locations need both latitude and longitude to be mappable.'],
    steps: [
      '1. Read each circle marker as one stored provider location with coordinates. A provider with multiple geocoded locations can have multiple markers.',
      '2. Use the Hospital, Clinic and Doctor buttons in the map legend to hide or show that type. All three types are shown initially; hiding every type leaves a “No visible locations” message, and selecting a type again restores its markers.',
      '3. Select a marker to open its popup. It shows the provider name and type, the location name when present, the stored address, and “Primary location” when that location is marked primary. Hospital, Clinic and Doctor markers use distinct colors.',
      '4. If the map says “No mappable locations,” no returned location has both coordinates. If the map background fails, read its warning; markers and type filters remain available.',
    ],
    result: 'The map displays all returned geocoded provider locations, with type-specific visibility controls and a popup for each location.',
    restrictions: [
      'The Dashboard map includes locations with coordinates regardless of provider Active/Inactive/Draft/Under review status or Published/Unpublished state. A marker does not certify that its provider is publicly discoverable.',
      'Type buttons only hide or show markers already returned; they do not change provider data, filter inventory counts or alter map coverage.',
      'Locations without either coordinate are omitted from the map, not evidence that the provider has no location record.',
      'The map is an administrative location overview, not a visitor map or an Analytics geographic report.',
    ],
  },
  {
    id: 'admin-dashboard-visiting-provider-calendar',
    title: 'Open and use the full visiting providers calendar',
    purpose: 'Browse active doctors’ recorded visiting periods by month and inspect the schedule for a selected date.',
    where: 'On /admin/dashboard, select “Visiting providers” → “View full calendar” to open /admin/visiting-providers.',
    who: 'Administrators signed in to the admin portal; this full calendar uses the admin-only dashboard-visits API.',
    prerequisites: ['Open the calendar while online. The initial month and Today date use the configured system timezone, not the computer’s local date.'],
    steps: [
      '1. Read the opened month and select Today to return to the server-reported current system date. Use Next month to browse forward; Previous month is disabled at the current month, so this page does not browse into past months.',
      '2. Select a date to open its Day agenda. The month view counts every scheduled visit whose start and end dates include that day, including a visit that spans multiple days.',
      '3. Read each agenda card’s scheduled date or date span, provider name, listed specializations and location. Select the card to open that provider’s administrator record.',
      '4. If the month is empty, read “No visiting providers scheduled this month.” If loading fails, use Try again; do not interpret an error as an empty schedule.',
    ],
    result: 'The calendar shows scheduled visiting periods for the selected month and the provider/location details for visits overlapping the selected day.',
    restrictions: [
      'The API includes only DOCTOR providers whose current provider status is ACTIVE and doctor availability is VISITING, with a recorded DoctorVisit overlapping the month and an end date on or after today. It does not require Published status.',
      'The calendar omits inactive providers, ongoing/stable availability, non-doctor providers, unscheduled doctors and visits that ended before today. It is not a complete historical visit archive.',
      'Scheduled visiting periods are not appointment slots or a promise of immediate availability. Contact the provider to confirm plans.',
      'The calendar is separate from date-filtered Analytics and from the Dashboard’s seven-day homepage-visits chart.',
    ],
  },
  {
    id: 'dashboard-analytics-glossary',
    title: 'Plain-language Dashboard and Analytics glossary',
    purpose: 'Clarify the status and reporting terms used by the operational Dashboard and Analytics manual.',
    where: 'Use these definitions wherever the corresponding labels appear in Dashboard or Analytics.',
    who: 'Administrators reading the Dashboard, provider inventory or Analytics reports.',
    prerequisites: ['No report or record needs to be open.'],
    steps: [
      '1. Active: the provider’s current management status is active. Active does not by itself mean the listing is published or publicly discoverable.',
      '2. Published: the provider listing is marked for public display. A listing also needs to be Active to be publicly discoverable in the directory.',
      '3. Pending review: a submitted provider application or proposed profile update is waiting for an administrator to decide it. That status alone does not mean an application is approved or a resulting listing is active and published.',
      '4. Primary location: the provider location marked as its main location. A provider may have other locations too.',
      '5. CSV: a plain-text table format that spreadsheet programs can open. Analytics CSV exports contain bounded report data and metadata, not a copy of every underlying record.',
      '6. Cohort: a group of records connected by when an event happened, such as member accounts created during the selected date range. A cohort report can show those records’ current state rather than their state at signup.',
      '7. Snapshots: values describing current state when a report is produced, such as today’s provider inventory or current verification status; they do not reconstruct what that state was in the past.',
    ],
    result: 'Status labels and reporting bases can be read without confusing public visibility, review progress, grouped events or current-state measures.',
    restrictions: [
      'Published and Active are separate provider fields; do not use either word as a substitute for the other.',
      'A current snapshot is not a period event count or historical snapshot. Check the report’s selected-period/current-snapshot basis.',
      'A cohort total counts its group; status counts within that cohort may describe present-day state.',
    ],
  },
];