import type { ManualTopic } from './types';

export const gettingStartedTopics: ManualTopic[] = [
  {
    id: 'public-find-care-start',
    title: 'Choose the right starting point',
    purpose: 'Understand what EquiConnected offers and choose the member or provider journey that matches your role.',
    where: 'Public homepage → Find a provider, Owners & riders, For vets, Visiting specialists, or Emergency',
    who: 'Visitors, horse owners, stable managers, and equine care providers',
    prerequisites: ['A web browser and an internet connection.'],
    steps: [
      'Open the EquiConnected public homepage.',
      'Choose Find a provider or Check all providers to begin the member directory journey; provider profiles and contact information require a member account.',
      'Choose Create your account when you are a horse owner or stable manager, or Register as a provider when you represent an equine practice.',
      'Read the Visiting specialists and Emergency sections for directory guidance; use a provider’s published contact details to discuss care directly.',
    ],
    result: 'You know which account type to create and where to begin exploring published provider information.',
    restrictions: [
      'The public homepage is informational; it does not provide public access to provider contact details.',
      'EquiConnected is a directory, not an emergency dispatch service. For urgent care, contact a local veterinary provider.',
    ],
  },
  {
    id: 'member-create-account',
    title: 'Create and verify a member account',
    purpose: 'Register as a horse owner, stable manager, or both so you can use the member directory and profile.',
    where: 'Public site → Create your account → /signup; emailed verification link → /verify-email',
    who: 'New horse owners and stable managers',
    prerequisites: [
      'A working email address that you can open.',
      'Your name, mobile number, country, and city.',
      'A password of at least 8 characters containing upper- and lowercase letters and a number.',
    ],
    steps: [
      'Open /signup and enter First name, Last name, Email address, Mobile number, country, state or province when requested, and city.',
      'Under I am joining as, select Horse Owner, Stable Manager, or Both.',
      'Enter and confirm your password, then accept the Terms & Conditions and Privacy Policy.',
      'Select Create account. If the page says Check your inbox, open the secure verification email and follow its link within 24 hours.',
      'After verification, continue to member sign-in. If the page says Account saved because email delivery failed, do not register again; use the available verification-resend option.',
    ],
    result: 'Your member account is created and, after email verification, ready for sign-in.',
    restrictions: [
      'Email verification is required before signing in; verification links expire after 24 hours and can only be used once.',
      'A successful account save with a failed email send is not a reason to submit a second registration.',
      'The role selected here controls which stable and horse profile sections are available.',
    ],
  },
  {
    id: 'public-contact-equiconnected',
    title: 'Contact the EquiConnected team',
    purpose: 'Send a general, provider-listing, or partnership enquiry to the EquiConnected team for an email response.',
    where: 'Public homepage → Contact us → Let’s talk horses',
    who: 'Visitors, members, provider practices, and potential partners',
    prerequisites: ['Your name and email address.', 'A message of at least 10 characters.'],
    steps: [
      'Go to the Contact us section of the public homepage.',
      'Enter Full name and Email, then choose an Enquiry type: General enquiry, Listing my practice, Partnership, or Other.',
      'Optionally enter Phone, then enter your question or request in Message.',
      'Review the Privacy Policy notice and select Send message.',
      'Wait for Thank you for reaching out and the confirmation that the team will respond by email.',
    ],
    result: 'Your enquiry is submitted to EquiConnected and a response is expected by email.',
    restrictions: [
      'The form requires a name, email, and message; phone is optional.',
      'This is a message to the EquiConnected team, not an in-app conversation with a provider.',
    ],
  },
  {
    id: 'public-subscribe-updates',
    title: 'Sign up for EquiConnected updates',
    purpose: 'Ask the EquiConnected team to keep you informed about platform updates.',
    where: 'Public homepage → Stay close to what’s happening next',
    who: 'Horse owners, stable managers, veterinary professionals, clinics, hospitals, and other interested visitors',
    prerequisites: ['A valid email address.', 'Your role.'],
    steps: [
      'Go to Stay close to what’s happening next on the public homepage.',
      'Under Your role, choose Horse owner, Stable manager, Veterinary professional, Clinic, Hospital, or Other.',
      'Enter your Email address and select Keep me posted.',
      'Wait for You’re on the list confirmation.',
    ],
    result: 'Your email and selected role are submitted for occasional EquiConnected updates.',
    restrictions: [
      'This updates subscription is not a member or provider account and does not grant access to the directory or provider portal.',
      'A role and valid email address are required.',
    ],
  },
];

export const providerTopics: ManualTopic[] = [
  {
    id: 'provider-public-registration',
    title: 'Register a provider practice',
    purpose: 'Submit an equine hospital, clinic, or independent professional application for verification and administrator review.',
    where: 'Public homepage → For veterinary professionals → Register as a provider → /provider/signup',
    who: 'Equine hospitals, clinics, and doctors / vets applying to join',
    prerequisites: [
      'A practice name, provider type, contact email and mobile number, professional title, years of experience, practice location, and working address.',
      'At least one specialization. Specialization and language choices must load before the application can be submitted.',
      'A password of at least 8 characters containing upper- and lowercase letters and a number.',
    ],
    steps: [
      'Open /provider/signup and enter Provider or practice name, then select Hospital, Clinic, or Doctor / Vet under Provider type.',
      'Enter First name, Last name, Email address, Mobile number, Professional title, and Years of experience.',
      'Select at least one item under Specializations; select relevant Languages if applicable.',
      'Enter Pincode / postal code. Choose a matching postal-location result when one appears, or complete the country, state or province, city, and Address fields yourself.',
      'Select Stable visit and enter Maximum Working Radius (KM) if you travel to stables. Select Emergency services available only if applicable and enter its Emergency contact number.',
      'Create and confirm a password, accept the Terms & Conditions and Privacy Policy, and select Submit provider application.',
      'Open the verification message and use its secure link within 24 hours. After verification, wait for administrator review; the confirmation page tells you whether the application was saved and email was sent.',
    ],
    result: 'Your provider registration is saved for verification and administrator review; the confirmation page says to expect follow-up by email.',
    restrictions: [
      'Submitting an application does not publish a provider listing or grant portal access. Administrator review follows email verification.',
      'If the page says Application saved because the verification email could not be sent, do not submit another application.',
      'Do not promise emergency response or availability based only on the checkbox; members are told to confirm directly with the provider.',
    ],
  },
  {
    id: 'provider-invitation-draft-submit',
    title: 'Complete an emailed provider invitation',
    purpose: 'Complete an invited clinic, hospital, or doctor profile, save a draft if needed, and submit the finished profile for review.',
    where: 'Invitation email → /provider/invite/<token> (also /provider/invitations/<token>)',
    who: 'The invited provider or practice contact',
    prerequisites: [
      'The complete invitation link from the invitation email; the link is validated before the form opens.',
      'Practice and professional details, contact information, specialization, and address information needed for the invited profile.',
      'A password of 8–128 characters with upper- and lowercase letters and a number for the invited provider portal account.',
    ],
    steps: [
      'Open the complete invitation link and wait for Validating your invitation… to finish.',
      'Check that the page heading matches the invitation type: Complete your doctor profile, Complete your hospital profile, or Complete your clinic profile.',
      'Review the prefilled form and complete the requested professional or practice details, contact details, practice address, specializations, languages, and visit or emergency service information.',
      'If the invitation has more than one saved practice address, use Keep <address> — <city> to choose the single address to retain before continuing.',
      'To pause, select Save draft. Confirm the Draft saved notice, then return later using the same invitation link.',
      'Before final submission, complete Provider portal account with Password and Confirm password. The login email is the invitation recipient email, separate from public profile contact emails.',
      'When the profile is ready, select Submit for review and resolve any field errors reported by the form.',
      'Wait for Submission received. The profile is under administrator review; the invited contact will be contacted by email when review is complete.',
    ],
    result: 'A saved draft remains available through the invitation link, or a submitted profile enters administrator review and shows a confirmation page.',
    restrictions: [
      'The invitation is not a provider sign-in or portal-password link. Do not share or forward its tokenized URL.',
      'Passwords are not saved in profile drafts; enter and confirm the password again before final submission. Portal access becomes available after administrator approval.',
      'An invalid, expired, cancelled, or already-completed invitation cannot be used to submit another profile; contact the sender or support team.',
      'The invitation form supports one practice address at a time; choose one saved address if asked to resolve multiple addresses.',
    ],
  },
  {
    id: 'provider-password-access',
    title: 'Set up or recover provider portal access',
    purpose: 'Create a provider portal password from an authorized setup email, or replace it from an administrator-issued recovery email.',
    where: 'Email link → /provider/setup-password?token=… or /provider/reset-password?token=…',
    who: 'Providers whose account has been approved and linked for portal access',
    prerequisites: [
      'A current provider portal setup or reset link issued for your account; recovery is initiated by an administrator.',
      'A new password containing 8–128 characters with upper- and lowercase letters and a number, plus a matching confirmation.',
    ],
    steps: [
      'Open the setup or reset link from the provider-access email and confirm whether the page says Set your password or Reset your password.',
      'Enter Password and Confirm password. Use the show/hide control if needed to check each entry.',
      'Select Set password for initial access or Reset password for recovery.',
      'After the success message, select Go to provider sign in and sign in at /provider/login using the email associated with your approved provider account.',
      'If the link is invalid, expired, or already used, or if you need a new recovery email, contact an administrator to issue a replacement link.',
    ],
    result: 'The password is set or reset and you can use the provider sign-in page to reach your provider account.',
    restrictions: [
      'Provider sign-in is reserved for approved provider accounts; public registration or invitation submission alone does not grant access.',
      'There is no self-service provider reset request on the sign-in page; an administrator must send the reset email.',
      'Setup and reset links are single-use and may expire or be replaced. Do not share them.',
    ],
  },
  {
    id: 'provider-sign-in',
    title: 'Sign in and sign out of the provider portal',
    purpose: 'Access the approved provider workspace and end the session when finished.',
    where: 'Provider portal → /provider/login; account workspace → /provider/account',
    who: 'Approved providers with a linked portal account and password',
    prerequisites: ['The email associated with the approved provider account and its current password.'],
    steps: [
      'Open /provider/login and enter Email address and Password.',
      'Select Sign in to provider portal.',
      'After authentication, use provider navigation to open Account for your profile, Insights for aggregate listing activity, or Messages to read and reply to member-started conversations.',
      'Select Logout in the provider navigation when you are finished.',
    ],
    result: 'You enter the provider workspace or return to provider sign-in after logging out.',
    restrictions: [
      'Only approved providers with portal access can sign in; members use /login instead.',
      'The provider portal does not expose publication or administrator operational controls. Published-profile changes are submitted for review.',
    ],
  },
  {
    id: 'provider-insights',
    title: 'Review provider performance insights',
    purpose: 'Review aggregate activity for the provider listing linked to your account and distinguish date-range activity from current profile totals.',
    where: 'Provider portal navigation → Insights (/provider/insights)',
    who: 'Signed-in provider account holders whose account is explicitly linked to exactly one provider listing',
    prerequisites: [
      'Sign in to an authorized provider portal account.',
      'The account must resolve to exactly one provider listing through an approved registration, completed invitation, or explicit provider portal access link.',
    ],
    steps: [
      'Select Insights in the provider navigation. The report is scoped to the listing linked to your provider account; there is no provider selector.',
      'Under Show activity, choose Last 7 days, Last 30 days, This month, or Choose dates. Choose dates reveals From and To date fields; select Apply dates to load the chosen period.',
      'Custom From and To dates are inclusive system-calendar dates. Choose a start date on or before the end date, no later than the displayed system-today date, and a range of 366 days or fewer. This month runs from the first day of the system-calendar month through system today.',
      'Read Activity in this period for Profile visits, Contact clicks, and New conversations. Each card includes its definition, coverage status and note, and a comparison when the prior equal-length period has complete coverage and a nonzero baseline.',
      'Open How this is counted on either Activity over time chart for its definition. The charts show daily Profile visits and Contact clicks; select View data table on either chart to switch to its date/value table.',
      'Read How members reached out for the selected period’s phone, email, and website contact-link activations.',
      'Read Current snapshot for Members who saved you, Ratings received, Visible written reviews, and Average rating. These are current profile totals and do not change with the selected date range.',
      'Check the displayed configured system timezone and Updated timestamp. Select Refresh to request the current report again; the page does not refresh on a timer. While a refresh is in progress, the page shows Updating the selected period.',
      'If the report has no data yet, the page says No insight data is available yet. A chart can separately say No covered data for this selection; these are different from a zero on a fully covered metric.',
      'If coverage is partial or unavailable, read the card’s note before interpreting the number. A partial value is marked with an asterisk; use the card’s comparison explanation when no percentage is available. Follow the page’s sign-in, access, or Try again message if a report request fails.',
    ],
    result: 'You can review date-scoped aggregate engagement, contact-link activations, coverage and comparisons, and separate current profile totals for your linked listing.',
    restrictions: [
      'The provider role and backend ownership resolution restrict the report to the one listing explicitly linked to your account. A missing or ambiguous listing link is not resolved by email matching and makes Insights unavailable.',
      'This report returns aggregate totals, not member identities, contact details, individual visit records, message contents, or review text. Ratings received and their average include non-deleted published or hidden ratings; Visible written reviews count only non-deleted published comments that are visible to members and non-empty.',
      'The audited page and API do not suppress small counts: low nonzero aggregate values can be displayed. Privacy comes from account/listing scope and aggregate-only reporting, not a minimum-count suppression rule.',
      'A covered zero means no recorded activity for that covered period. Not available or unavailable/unknown coverage is not a zero; partial coverage excludes dates before collection began. A first collection calendar date is conservatively marked partial.',
      'The selected-period cards, trends, and contact breakdown use inclusive dates in the configured system timezone, with timestamp bounds converted to UTC. Current snapshot totals are independent of the selected period.',
      'Profile visits count successful profile loads and revisits; they are not unique people or appointments. Contact clicks count link activations, not completed calls, emails, bookings, or leads. New conversations count durable conversations for the currently authorized provider account and exclude replies. These measures do not establish a care outcome.',
      'The page has no export control. Do not expect a downloadable report or infer that a click or conversation resulted in a booking.',
    ],
  },
  {
    id: 'provider-private-messages',
    title: 'Open and reply to private member messages',
    purpose: 'Read member-initiated private conversations linked to your provider listing and reply from the provider portal.',
    where: 'Provider portal navigation → Messages (/provider/messages) → Inbox → conversation',
    who: 'Signed-in, verified provider account holders with an active, approved portal account explicitly linked to an active published provider listing',
    prerequisites: [
      'A provider account that is active, verified, approved for portal access, and unambiguously linked to the active published listing.',
      'A member must start the conversation; providers cannot start a new conversation from the provider portal.',
    ],
    steps: [
      'Select Messages in the provider navigation. The navigation badge and each inbox conversation show unread counts when unread messages are present.',
      'Select a member conversation in Inbox to open its thread. The member’s name, account email, and phone are shown in the shared contact section when the member agreed to share them.',
      'Read the thread; received messages are marked read when they become visible in the open conversation. Write a plain-text reply of up to 5,000 characters and select Send reply.',
      'If a send fails, follow the inline error; a request-limit message means wait and try later. If the page cannot confirm whether a send was saved, use Retry same message rather than composing a duplicate.',
      'Use Email member or Call member for an optional direct contact in your email or phone application; these are separate from the in-app reply.',
      'Use Previous and Next to browse inbox pages when there are more than 20 conversations. Select Load older messages to fetch earlier thread history in batches of 50.',
      'The inbox and open thread refresh automatically while the page is visible, about every 15 seconds, and refresh when you return to the page. Use Retry loading inbox or Retry loading conversation if a load error offers that control.',
    ],
    result: 'You can read and reply to conversations members started for the provider account linked to your listing.',
    restrictions: [
      'Only verified members and their specifically linked provider account can participate; a provider cannot initiate a conversation or access another listing’s conversation.',
      'The member’s name, account email, and phone are shared with the linked provider account only after the member consents at conversation start. Do not treat a message as permission to disclose those details elsewhere.',
      'Message text and shared contact details are encrypted at rest and protected in transit over HTTPS, but messaging is not end-to-end encrypted. The composer accepts plain text only; do not include sensitive medical or payment information.',
      'Email notices are separate, best-effort notifications and do not contain conversation text. A notice can fail while the accepted message remains saved in the inbox; an email notice or a sent message does not guarantee inbox delivery, a reply, care, or an appointment.',
      'Private messaging does not schedule or book appointments. Contact the member separately if you need to discuss arrangements.',
      'If the linked provider account or listing is unavailable, ambiguous, or encryption is unavailable, messaging may be disabled; use appropriate direct contact options instead.',
    ],
  },
  {
    id: 'provider-profile-edit',
    title: 'Update provider details, services, and professional information',
    purpose: 'Maintain the provider details that members use to understand your practice and care services.',
    where: 'Provider portal → Manage your submitted profile → Basic details, Professional details, and Services',
    who: 'Signed-in provider account holders',
    prerequisites: ['Sign in to an approved provider account.', 'Wait for Manage your submitted profile to load.'],
    steps: [
      'Open Basic details and update Provider or practice name and Website. The Description field is shown for non-doctor provider profiles.',
      'Open Professional details and update Years of experience. Doctor profiles can also maintain Professional title, Biography, Experience notes, and Qualifications.',
      'Open Services and use the Specializations checkboxes, Select all, or Clear all to maintain specialties shown on your profile.',
      'In Visit and emergency services, select Offers stable visits and enter Maximum working radius (km) when you provide stable visits.',
      'Select Emergency services available only if offered; enter the required Emergency contact number when it is enabled.',
      'Select Save profile. Use the on-page review notice to distinguish a pending, approved, or declined update.',
      'If an unpublished draft or proposed update is present and you need to restore the latest approved listing, select Discard draft and reload approved listing and confirm the resulting notice.',
    ],
    result: 'Your updated provider details are saved to your unpublished profile or submitted as a review request for a published listing.',
    restrictions: [
      'Members continue to see the last approved version of a published listing until an administrator approves the proposed update.',
      'A rejected update can be revised and saved again; use Revise and resubmit when that action label is shown.',
      'Portal users cannot publish listings or change operational controls.',
    ],
  },
  {
    id: 'provider-locations-contact',
    title: 'Maintain provider locations and contact details',
    purpose: 'Keep member-facing practice locations, primary address, telephone numbers, and email addresses accurate.',
    where: 'Provider portal → Manage your submitted profile → Contact & location',
    who: 'Signed-in provider account holders',
    prerequisites: ['Sign in to an approved provider account.', 'Have the correct practice address and member-facing contact details.'],
    steps: [
      'Open Contact & location. Under Locations, select Add location to create an entry.',
      'Complete Address line 1 and City; add Location name, Address line 2, State, province, or emirate, Country, Postal code, Latitude, or Longitude when applicable.',
      'Select the Primary location radio control for the address members should see first. Select Remove to remove an unwanted location.',
      'Under Contact details, add or update phone and email entries, and use the field controls to select primary entries.',
      'Select Save profile to save your changes or submit them for review when the listing is published.',
    ],
    result: 'The revised locations and contact collections are saved with your provider profile or submitted as a review request.',
    restrictions: [
      'Address and contact changes to a published listing are not visible to members until approved.',
      'Enter only accurate business contact information intended for member contact.',
    ],
  },
  {
    id: 'provider-profile-photos',
    title: 'Upload and review provider profile photos',
    purpose: 'Add accessible photos to a provider profile and choose which image appears first.',
    where: 'Provider portal → Manage your submitted profile → Photos',
    who: 'Signed-in provider account holders',
    prerequisites: [
      'A JPEG, PNG, GIF, or WebP image file no larger than 10 MB per image.',
      'Sign in to an approved provider account.',
    ],
    steps: [
      'Open Photos and select Add photos, or drop images into the photo area.',
      'For each staged file, optionally enter Alt text for screen readers and an Image title caption. Remove any staged photo you do not want to upload.',
      'Select Upload photo or Upload photos and wait until uploads finish.',
      'For each uploaded profile photo, update Alt text or Image title as needed; use Show first to set the listing thumbnail and Remove to remove a photo.',
      'Select Save profile. A successful upload alone is not enough to add a photo to the provider profile.',
      'Review the notice: unpublished profiles save immediately; changes to a published listing, including photos, await administrator review.',
    ],
    result: 'Uploaded photos are included in your saved provider profile or its pending review request, with the selected thumbnail and accessible description.',
    restrictions: [
      'Wait for uploads to finish before saving profile changes.',
      'Staged photos are not uploaded, and uploaded photos are not part of the profile until Save profile is selected.',
      'Members continue to see the approved photos on a published listing until the photo update is approved.',
    ],
  },
  {
    id: 'provider-visiting-schedule',
    title: 'Review visit history and propose visiting trips',
    purpose: 'Check recorded visiting periods and submit proposed trip dates and locations from an eligible visiting-doctor profile.',
    where: 'Provider portal → Manage your submitted profile → Visits',
    who: 'Providers whose doctor profile is marked Visiting and can schedule visits',
    prerequisites: [
      'Sign in to the provider portal.',
      'The Visits tab is only available when the profile has doctor fields, Visiting availability, and visit-scheduling permission.',
      'For a proposed trip, provide a start date, end date, address line 1, and city.',
    ],
    steps: [
      'Open Visits. Review Recorded visit history under Previous, Current, and Upcoming; recorded visits are read-only.',
      'Under Proposed visits, select Add visit.',
      'Enter Visit start date and Visit end date, then complete Visit location details. New visits must start today or later, and the end date must be on or after the start date.',
      'Select Add visit for additional proposals or Remove on a proposed visit you no longer want to include.',
      'Select Save profile to submit the proposed additions. Correct any validation message about missing dates, location details, or overlapping date ranges.',
      'Check the profile review notice: additions on a published listing remain proposals until the administrator approves the profile update.',
    ],
    result: 'Recorded visits remain read-only; valid proposed trips are saved with the profile and may require approval before appearing in the public visiting schedule.',
    restrictions: [
      'Visit dates cannot overlap another recorded visit or another proposed visit.',
      'Proposed visits are not part of recorded history until saved and, where review is required, approved.',
      'Providers without eligible Visiting doctor account fields do not see the Visits tab.',
    ],
  },
  {
    id: 'provider-read-member-feedback',
    title: 'Read member feedback on your provider profile',
    purpose: 'Review the member-visible rating summary and published comments displayed for your provider account.',
    where: 'Provider portal → Member feedback → What members are saying',
    who: 'Signed-in provider account holders',
    prerequisites: ['Sign in to the provider portal.', 'Member feedback appears when a review has been made visible to members.'],
    steps: [
      'On Manage your submitted profile, select Member feedback.',
      'Read the average rating, review count, and visible review comments in What members are saying.',
      'Select Close to close the feedback panel.',
    ],
    result: 'You can review the member-visible feedback associated with your provider listing.',
    restrictions: [
      'The provider workspace provides read-only member-visible reviews; it does not provide member identity or a reply control.',
      'Hidden or unpublished comments are not shown in this panel.',
    ],
  },
];

export const memberTopics: ManualTopic[] = [
  {
    id: 'member-sign-in',
    title: 'Sign in to the member space',
    purpose: 'Open your verified member account and continue to the directory and personal profile.',
    where: 'Member sign-in → /login; member workspace → /providers',
    who: 'Horse owners, stable managers, and members with both roles',
    prerequisites: ['A verified member account and its email address and password.'],
    steps: [
      'Open /login and enter Email address and Password.',
      'Select Sign in. If email verification has just completed, the page may prefill your email and show a success notice.',
      'Use the member navigation to open Providers, Profile, or Saved providers.',
      'Open the account menu and select Sign out when finished.',
    ],
    result: 'You enter the protected member space and can open the areas permitted by your account roles.',
    restrictions: [
      'Unverified member accounts cannot sign in. Provider accounts use /provider/login instead.',
      'There is no password-recovery control on the member sign-in page. Use Contact us on the public homepage if you need help with account access.',
    ],
  },
  {
    id: 'member-personal-profile',
    title: 'Update your member contact and location profile',
    purpose: 'Keep your personal name, mobile number, and location current for your EquiConnected account.',
    where: 'Member space → Profile → Account, contact, and location',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Have your current contact and location information ready.'],
    steps: [
      'Open Profile and review the Profile readiness summary and Account, contact, and location completion status.',
      'Update First name, Last name, and Mobile number. Your verified email is displayed as account status and cannot be changed here.',
      'Under Personal location, update your address, country, state or province when used in your country, city, and postal code.',
      'Select Save personal information and wait for the success or error notice.',
    ],
    result: 'Your member contact and personal location information are saved, and profile readiness reflects the saved information.',
    restrictions: [
      'Your verified email cannot be edited on this page.',
      'State or province is required only where the selected country uses one.',
    ],
  },
  {
    id: 'member-stable-profile',
    title: 'Maintain your stable manager profile',
    purpose: 'Record stable identity, location, and contact details for the stable manager role.',
    where: 'Member space → Profile → Stable Manager',
    who: 'Signed-in members with the stable_manager role',
    prerequisites: ['Sign in with an account that has the stable manager role.'],
    steps: [
      'Open Profile and find the Stable Manager section.',
      'Enter Stable name and, if useful, Stable description.',
      'Update the stable location using the location fields.',
      'Enter Contact name, Contact email, and Contact phone.',
      'Select Save stable profile and confirm the saved notice.',
    ],
    result: 'Your stable profile is saved independently from your personal member information.',
    restrictions: [
      'The Stable Manager section is shown only to accounts with the stable_manager role.',
      'A stable photo is not part of this profile.',
    ],
  },
  {
    id: 'member-horse-profiles',
    title: 'Add and manage horse profiles',
    purpose: 'Keep a profile for each horse you care for, including required identity basics and optional useful details.',
    where: 'Member space → Profile → Horse Owner',
    who: 'Signed-in members with the horse_owner role',
    prerequisites: ['Sign in with an account that has the horse owner role.', 'A horse name and sex are required to create a horse profile.'],
    steps: [
      'Open Profile and find Horse Owner. Select Add horse.',
      'Enter Horse name and select Sex: Mare, Gelding, Stallion, Filly, Colt, or Other.',
      'Add optional Registered name, Breed, Date of birth, Color, Primary discipline, Registration number, Microchip number, or Description when useful.',
      'Select Save horse. To update an existing record, select Edit, make changes, and save.',
      'To add an image, select Upload photo and choose a JPEG, PNG, GIF, or WebP image no larger than 10 MB. Use Remove photo to delete the current photo.',
      'To permanently remove a horse, select Remove and confirm the browser prompt.',
    ],
    result: 'Each horse is saved as a separate entry in your member profile, and the horse section’s completion status updates.',
    restrictions: [
      'Name and sex are the only horse fields needed for profile completion; extended details are optional.',
      'Horse profile controls are shown only to accounts with the horse_owner role.',
      'Removing a horse cannot be undone.',
    ],
  },
  {
    id: 'member-provider-directory',
    title: 'Find and filter providers',
    purpose: 'Search the member directory for published equine professionals, clinics, and hospitals matching your care needs.',
    where: 'Member space → Providers (/providers)',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Provider profiles and contact details are members-only.'],
    steps: [
      'Open Providers and enter a term in Provider name or use Visit type, Specialization, and Region / emirate.',
      'Select More filters to optionally set Provider type, Minimum rating, or Emergency services only.',
      'Select Apply filters to apply the draft filter choices. Select Clear filters to reset them.',
      'Choose Relevance or Name A–Z, switch between Grid view and List view, and use the page controls to browse results.',
      'For distance options, select Sort closest first or Within working radius and allow the browser to share your current location when prompted.',
      'Select View profile or Contact details on a result to open its profile or contact section.',
    ],
    result: 'The directory displays published providers matching the applied filters and offers navigation to each provider’s member-visible profile.',
    restrictions: [
      'Location options request browser location only after you choose one. After a refresh, choose a location option again to restore distance results.',
      'The working-radius filter uses the provider’s listed location and radius, not your horse’s stable.',
      'Directory visit periods are not appointment slots; contact providers to confirm timing and availability.',
    ],
  },
  {
    id: 'member-save-providers',
    title: 'Save and revisit providers',
    purpose: 'Keep a personal shortlist of providers available from the directory.',
    where: 'Member space → Providers or a provider profile → Save for later / Saved providers',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'The provider must be available in the member directory.'],
    steps: [
      'Find a provider in the directory or open its provider profile.',
      'Select Save for later on the provider card or profile to add it to your shortlist.',
      'Open Saved providers from the member navigation or the directory’s saved-provider control.',
      'Select Saved on a provider to remove it from your shortlist.',
    ],
    result: 'Saved providers appear in your Saved providers directory view and can be removed at any time.',
    restrictions: [
      'Saved providers is a member-only shortlist, not a contact or appointment request.',
      'A provider removed from the available directory may no longer be openable from the saved list.',
    ],
  },
  {
    id: 'member-provider-profile-contact-photos',
    title: 'Review a provider profile, contact details, and photos',
    purpose: 'Understand provider-shared services, locations, reviews, and ways to contact a practice directly.',
    where: 'Member space → Providers → View profile',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Open a published provider profile from the directory or visiting calendar.'],
    steps: [
      'Use the profile section links About, Qualifications, Care & services, Locations, Reviews, and Gallery when those sections are present.',
      'Review the provider type, shared profile description, qualifications, specializations, languages, and listed service capabilities.',
      'Review Locations & service area and any Recorded visits; use Contact provider to jump to the contact card.',
      'Use the contact card’s Phone, Email, or Website link to contact the provider directly.',
      'When the Message provider action is available on the profile, select it to start a private conversation; messaging availability depends on the provider listing and linked account.',
      'To view profile photos, select View photos or a Gallery image; select a thumbnail to change photos and select Close or press Escape to exit the gallery.',
    ],
    result: 'You can inspect information the provider has published, use available direct contact links, and start an eligible private conversation.',
    restrictions: [
      'Private messaging is available only to signed-in members when the provider listing and its linked portal account are eligible; use the published direct contact options if messaging is unavailable.',
      'Messages do not book appointments. Recorded visit dates are not appointment slots or a guarantee of immediate availability.',
      'Street addresses are not shown publicly on the homepage; ask the provider about location and availability.',
      'Emergency service information is provider-shared; confirm availability and response directly.',
    ],
  },
  {
    id: 'member-private-messages',
    title: 'Start and manage private messages with providers',
    purpose: 'Start an eligible private conversation from a provider profile, then read and reply to messages in your member inbox.',
    where: 'Member navigation → Messages (/member/messages); member space → Providers → provider profile → Message provider',
    who: 'Signed-in, email-verified members',
    prerequisites: [
      'Sign in to a verified member account.',
      'To start a conversation, your member profile must include your name, account email, and phone number.',
      'The provider listing must be active and published with one eligible, explicitly linked provider portal account; the member must agree to share the displayed contact details.',
    ],
    steps: [
      'Select Messages in the member navigation to open your inbox. To start a conversation, open an eligible provider profile and select Message provider.',
      'On the new conversation screen, review the provider availability and the contact preview (your name, account email, and phone). Complete your member profile if a required detail is missing.',
      'Select the consent checkbox to share those contact details with that provider, enter a plain-text message of up to 5,000 characters, and select Send private message. A successful send opens the saved conversation.',
      'Select a conversation in Inbox to read its thread. Enter a plain-text reply of up to 5,000 characters and select Send reply; use Retry same message if the page cannot confirm whether the send was saved.',
      'Follow inline errors if the message cannot be sent. Complete your contact profile or consent when requested, wait and try later if you reach the message limit, and use direct contact options if the provider or encryption is unavailable.',
      'Received messages are marked read when they become visible in the open conversation. The navigation badge and inbox rows show unread counts.',
      'Use Previous and Next to browse inbox pages when there are more than 20 conversations. Select Load older messages to fetch earlier thread history in batches of 50.',
      'The inbox and open thread refresh automatically while the page is visible, about every 15 seconds, and refresh when you return to the page. Use Retry loading inbox or Retry loading conversation if a load error offers that control.',
    ],
    result: 'Your accepted message appears in a private conversation with the provider account linked to that listing, and you can read and reply to the thread from your inbox.',
    restrictions: [
      'Only verified members can use messaging. You cannot start a conversation when the listing is unavailable, its provider account is missing or ambiguous, or messaging encryption is unavailable; use the provider’s published direct contact options instead.',
      'Your name, account email, and phone are shared with that linked provider account only after you consent. Messages and contact details are encrypted at rest and protected in transit over HTTPS, but are not end-to-end encrypted.',
      'The composer accepts plain text only. Do not include sensitive medical or payment information.',
      'Email notices are separate, best-effort notifications and do not contain conversation text. A notice can fail while the accepted message remains saved in your inbox; sending a message or email notice does not guarantee inbox delivery, a provider reply, care, or an appointment.',
      'Private messaging does not schedule or book appointments. For urgent care, contact a local veterinary provider directly.',
    ],
  },
  {
    id: 'member-visiting-calendar',
    title: 'Explore the visiting provider calendar',
    purpose: 'Browse published visiting periods by month and open the provider profile for details.',
    where: 'Member space → Providers → Visiting providers → View calendar (/providers/visiting-calendar)',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'The directory’s visiting-provider section is available whether or not current visits are listed.'],
    steps: [
      'From the directory, open View calendar in the Visiting providers section.',
      'Use Previous month or Next month to change the displayed schedule, or select Today to return to the current date.',
      'Select a date in the calendar to see its day agenda; on smaller screens use the listed dates.',
      'Open a visit card and select Provider profile to review the provider and use the published contact details.',
      'Select Provider directory to return to the directory.',
    ],
    result: 'You can see which visiting periods are recorded for a selected date and open the corresponding provider profile.',
    restrictions: [
      'Scheduled visiting periods are not appointment slots or a guarantee of immediate availability. Contact the provider to confirm plans.',
      'The calendar coverage is independent of the directory filters you applied.',
    ],
  },
  {
    id: 'member-provider-reviews',
    title: 'Write, edit, or remove a provider review',
    purpose: 'Share a rating and optional review for a provider and manage your own review.',
    where: 'Member space → Provider profile → Reviews; account menu → My Reviews & Feedback',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Open the provider profile you want to review.'],
    steps: [
      'In Reviews, select Write a review or Edit your review.',
      'Choose Your rating from 1 to 5 stars and optionally enter a Comment of up to 2,000 characters.',
      'Select Submit review or Update review and wait for the saved notice.',
      'To manage all your reviews, open My Reviews & Feedback and choose Provider reviews.',
      'Select Edit review to change a review that is not hidden; saving an edit sends it back for moderation.',
      'Select Delete and confirm to remove a review.',
    ],
    result: 'Your review is saved and its current publication or moderation status appears on the provider profile and in My Reviews & Feedback.',
    restrictions: [
      'New reviews and edits await moderation; only published comments appear to other members.',
      'A hidden review comment is private and cannot be edited from the provider profile; its approved rating may be retained.',
      'Deleting a review cannot be undone.',
    ],
  },
  {
    id: 'member-private-feedback',
    title: 'Send private feedback to EquiConnected',
    purpose: 'Send a private note about the website, directory, provider experience, account, or another platform topic.',
    where: 'Member account menu → Feedback on EquiConnected; or My Reviews & Feedback → Feedback on EquiConnected',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Have a feedback category and message ready.'],
    steps: [
      'Open the account menu and select Feedback on EquiConnected, or open My Reviews & Feedback and select the same action.',
      'Choose a category under What is this about?: Website / App, Search & Matching, Provider Experience, Account / Profile, Technical Issue, Suggestion, or Other.',
      'Optionally add an Overall experience rating and Subject, then enter Your feedback.',
      'Select Send feedback and wait for confirmation that the note is private to you and the EquiConnected team.',
      'To close an unsent form with content, choose Keep writing or confirm Discard; submitted notes can later be reviewed under System feedback in My Reviews & Feedback.',
    ],
    result: 'Your note is sent privately to the EquiConnected team and appears in the System feedback list.',
    restrictions: [
      'Feedback is private to you and the EquiConnected team; it is not a message to the provider.',
      'A category and message are required; the optional subject is limited to 200 characters and the message to 5,000 characters.',
    ],
  },
  {
    id: 'member-reviews-feedback-management',
    title: 'Manage reviews and platform feedback',
    purpose: 'Review your submitted activity, check moderation or response status, and manage actions that remain available.',
    where: 'Member account menu → My Reviews & Feedback (/my-reviews)',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.'],
    steps: [
      'Open My Reviews & Feedback and choose Provider reviews or System feedback.',
      'Use the activity list and Previous / Next pagination to locate a submitted item.',
      'For an eligible provider review, choose Edit review, update Rating or Your review, then select Save review; choose Delete and confirm if you want to remove it.',
      'For Pending system feedback, choose Edit feedback to revise it or Withdraw and confirm to remove it from your active feedback list.',
      'Read the displayed status, moderator note, or EquiConnected team response to understand the item’s current state.',
    ],
    result: 'You can track provider review moderation and platform feedback status and make the changes permitted for each item.',
    restrictions: [
      'Only Pending platform feedback can be edited or withdrawn from this page.',
      'Editing a provider review returns it to moderation. Hidden reviews cannot be edited.',
      'The System feedback list is private; it is not a messaging inbox with providers.',
    ],
  },
  {
    id: 'member-browsing-history',
    title: 'Review and restore browsing history',
    purpose: 'Revisit provider profiles and restore searches recorded in your member browsing history.',
    where: 'Member account menu → Recent activity / View all → Browsing history (/history)',
    who: 'Signed-in members',
    prerequisites: ['Sign in to a member account.', 'Browsing history records eligible searches and provider views from when history is enabled.'],
    steps: [
      'Open the account menu to review Recent activity, or choose View all to open Browsing history.',
      'Review Provider search entries and their recorded filter summary, or provider profile entries and their date.',
      'Choose Restore search to return to a recorded directory search, or Open profile to reopen an available provider.',
      'Use Previous or Next to browse additional activity pages.',
    ],
    result: 'You can restore a recorded search or reopen a provider profile that is still available.',
    restrictions: [
      'History is private to your own account; entries from before history was enabled are not added retroactively.',
      'Unavailable provider profiles cannot be reopened from history.',
    ],
  },
];

export const troubleshootingTopics: ManualTopic[] = [
  {
    id: 'troubleshoot-email-verification',
    title: 'A member or provider verification link does not work',
    purpose: 'Resolve common email-verification problems without creating duplicate accounts or applications.',
    where: 'Signup confirmation, verification email, and /verify-email',
    who: 'New members and provider applicants',
    prerequisites: ['Access to the email address used during registration.', 'The verification message or its account email.'],
    steps: [
      'Check that you opened the complete verification link from the registration email.',
      'If the link has expired, was already used, or is invalid, use the verification-resend option shown on the relevant page when available.',
      'Check your spam or junk folder and confirm you are checking the address shown on the confirmation page.',
      'If registration said Account saved or Application saved because email delivery failed, do not register again; request the available resend or contact support.',
      'After successful verification, continue to the sign-in destination shown for your account.',
    ],
    result: 'You can continue using a current verification link or request help without creating a duplicate registration.',
    restrictions: [
      'Verification links expire after 24 hours and can be used only once.',
      'Provider applications still require administrator review after email verification.',
    ],
  },
  {
    id: 'troubleshoot-provider-portal-access',
    title: 'I cannot sign in to the provider portal',
    purpose: 'Check provider account eligibility and password-link status when provider sign-in is unavailable.',
    where: 'Provider portal → /provider/login and password email links',
    who: 'Provider applicants and approved provider account holders',
    prerequisites: ['The email address associated with the provider account.'],
    steps: [
      'Confirm that you are using /provider/login and the email associated with your approved provider account.',
      'If you have not received provider portal access after approval, contact an administrator to check account linkage and send the appropriate setup email.',
      'If you received a setup or reset email, open its complete link and follow Set your password or Reset your password.',
      'If the link reports invalid, expired, or already used, contact an administrator for a replacement link.',
      'If a password reset is needed, ask an administrator to send a recovery email; retry sign-in after you set the new password.',
    ],
    result: 'You can resume sign-in with a valid provider account or give the administrator the information needed to restore access.',
    restrictions: [
      'A provider registration or invitation submission alone does not provide portal access.',
      'Providers cannot request a password-reset email themselves from the sign-in page.',
      'Do not share password links or attempt to bypass provider access controls.',
    ],
  },
  {
    id: 'troubleshoot-provider-profile-review',
    title: 'My provider changes or photos are not visible yet',
    purpose: 'Understand why a profile change saved successfully but the public listing still shows its previous approved version.',
    where: 'Provider portal → Manage your submitted profile → review status notices',
    who: 'Signed-in provider account holders',
    prerequisites: ['Sign in to the provider portal and review the notice at the top of the profile page.'],
    steps: [
      'Check whether the profile update notice says it is awaiting administrator review.',
      'Remember that a successful photo upload must also be included by selecting Save profile.',
      'If the update is pending, continue revising the draft if necessary and wait for the review decision.',
      'If the update is declined, read the displayed reason, make corrections, and select Revise and resubmit or Save profile.',
      'If a published profile update was approved but is still unavailable, reload the provider account and contact support with the provider name and update status.',
    ],
    result: 'You can tell whether the change is still pending, needs revision, or requires support after approval.',
    restrictions: [
      'Members continue to see the last approved version of a published provider listing until the update is approved.',
      'Uploads alone do not add photos to the profile; uploaded photos must be included by saving the profile.',
    ],
  },
  {
    id: 'troubleshoot-directory-location',
    title: 'Distance filters or provider results are unavailable',
    purpose: 'Restore directory search results when location permission, filter state, or a temporary loading error prevents results.',
    where: 'Member space → Providers directory → More filters',
    who: 'Signed-in members using provider search',
    prerequisites: ['Sign in to a member account.', 'Browser location permission is optional and is only requested when you choose a distance filter.'],
    steps: [
      'If the directory reports that providers could not be loaded, select Try Again; your filters are retained.',
      'If Sort closest first or Within working radius has no location, choose that option again and allow browser location access.',
      'If permission was denied, review your browser’s site-location permission and retry; location filtering remains off until access succeeds.',
      'If you do not want to use location, turn off both distance options or select Clear filters, then browse using name, type, specialty, region, rating, or emergency filters.',
      'If filter choices are unavailable, you can still browse results and use the other available filters.',
    ],
    result: 'You can resume a directory search with location enabled or continue browsing without distance filters.',
    restrictions: [
      'Location-based search requires an explicit choice and browser permission; after a page refresh, choose again to enable distance results.',
      'Do not infer that a provider is unavailable solely from a distance-filter or temporary loading failure.',
    ],
  },
];