"""Isolated contact-key and admin-seed regression tests.

These tests use only synthetic key material and mocked bootstrap dependencies.
They deliberately avoid constructing Settings, loading dotenv files, or opening
a database.
"""
import base64
import contextlib
import importlib.util
import json
import os
from pathlib import Path
import sys
import types
import unittest
from unittest.mock import Mock, patch
from uuid import UUID


BACKEND = Path(__file__).resolve().parents[1]
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.services import contact_encryption  # noqa: E402
from app.services import messaging_encryption  # noqa: E402


# Fixed, distinct synthetic fixtures. Never load key material from process
# environment or a dotenv file in this module.
C = b"A" * 32
I = b"B" * 32
M = b"C" * 32
J = b"D" * 32


def encoded(value):
    return base64.b64encode(value).decode("ascii")


def synthetic_settings(
    *,
    keyring=None,
    active_id="current",
    index_key=I,
    secret_key="synthetic-jwt-secret",
    messaging_keyring="",
    messaging_active_id="messaging-active",
):
    if keyring is None:
        keyring = {"current": encoded(C)}
    if isinstance(keyring, dict):
        keyring = json.dumps(keyring)
    return types.SimpleNamespace(
        CONTACT_ENCRYPTION_KEYRING=keyring,
        CONTACT_ENCRYPTION_ACTIVE_KEY_ID=active_id,
        CONTACT_BLIND_INDEX_KEY=encoded(index_key) if isinstance(index_key, bytes) else index_key,
        SECRET_KEY=secret_key,
        MESSAGING_ENCRYPTION_KEYRING=messaging_keyring,
        MESSAGING_ENCRYPTION_ACTIVE_KEY_ID=messaging_active_id,
    )


class ContactEncryptionTests(unittest.TestCase):
    def validate_with(self, settings):
        with patch.object(contact_encryption, "get_settings", return_value=settings):
            return contact_encryption._key_material()

    def test_unavailable_exception_has_safe_default_reason(self):
        error = contact_encryption.ContactEncryptionUnavailable()
        self.assertEqual(error.reason, "contact_configuration_invalid")

    def test_contact_crypto_roundtrip_and_stable_blind_index_with_optional_messaging(self):
        for messaging_ring in ("", "not-json", '{"bad":"%%%"}'):
            with self.subTest(messaging_ring=messaging_ring):
                settings = synthetic_settings(messaging_keyring=messaging_ring)
                with patch.object(contact_encryption, "get_settings", return_value=settings):
                    envelope = contact_encryption.encrypt_contact(
                        "Private@example.test",
                        table="members",
                        record_id="synthetic-row-1",
                        field="email",
                    )
                    self.assertEqual(
                        contact_encryption.decrypt_contact(
                            envelope,
                            table="members",
                            record_id="synthetic-row-1",
                            field="email",
                        ),
                        "Private@example.test",
                    )
                    first = contact_encryption.contact_blind_index(
                        " Private@example.test ",
                        table="members",
                        field="email",
                    )
                    second = contact_encryption.contact_blind_index(
                        "private@EXAMPLE.test",
                        table="members",
                        field="email",
                    )
                self.assertEqual(first, second)
                self.assertEqual(len(first), 64)

    def test_retained_legacy_contact_key_decrypts_after_active_key_rotation(self):
        # Generated once using HEAD's contact_encryption.py, the synthetic
        # old-contact key, and a deterministic nonce. This is a fixed legacy
        # ciphertext fixture, not generated by the implementation under test.
        legacy_envelope = (
            "v1.old-contact."
            "AAECAwQFBgcICQoLIsiRULWPykABCfKUsowmquJTu1wUDs7k4eysjMKCsE0xImiqjP7O0stQWYA="
        )
        settings = synthetic_settings(
            keyring={"old-contact": encoded(C), "current-contact": encoded(M)},
            active_id="current-contact",
        )
        with patch.object(contact_encryption, "get_settings", return_value=settings):
            active_id, _keys, _index_key = contact_encryption._key_material()
            plaintext = contact_encryption.decrypt_contact(
                legacy_envelope,
                table="members",
                record_id="retained-key-row",
                field="email",
            )
        self.assertEqual(active_id, "current-contact")
        self.assertEqual(plaintext, "legacy@compatibility.example")

    def test_contact_blind_index_matches_fixed_prechange_hmac_golden(self):
        settings = synthetic_settings()
        with patch.object(contact_encryption, "get_settings", return_value=settings):
            actual = contact_encryption.contact_blind_index(
                " Person@Example.Test ",
                table="members",
                field="email",
            )
        self.assertEqual(
            actual,
            "22a4bd87daa2e3e28287643361eab752889aa4c99f9ad402201cc44e2176acd3",
        )

    def test_invalid_contact_configuration_has_specific_safe_reasons(self):
        valid_ring = {"current": encoded(C)}
        duplicate_ring = {"current": encoded(C), "retained": encoded(C)}
        cases = (
            ("contact_keyring_missing", {"keyring": ""}),
            ("contact_active_key_id_invalid", {"active_id": "bad id"}),
            ("contact_keyring_invalid", {"keyring": "not-json"}),
            ("contact_keyring_invalid", {"keyring": "[]"}),
            ("contact_key_id_invalid", {"keyring": {"bad id": encoded(C)}}),
            ("contact_key_encoding_invalid", {"keyring": {"current": "%%%not-base64%%%"} }),
            (
                "contact_key_encoding_invalid",
                {
                    "keyring": {
                        "current": base64.urlsafe_b64encode(bytes([251]) * 32).decode("ascii")
                    }
                },
            ),
            ("contact_key_encoding_invalid", {"keyring": {"current": None}}),
            ("contact_key_length_invalid", {"keyring": {"current": encoded(C[:16])}}),
            ("contact_active_key_missing", {"keyring": {"retained": encoded(C)}}),
            ("contact_keys_duplicated", {"keyring": duplicate_ring}),
            ("contact_blind_index_missing", {"index_key": ""}),
            ("contact_blind_index_encoding_invalid", {"index_key": "%%%not-base64%%%"}),
            ("contact_blind_index_length_invalid", {"index_key": encoded(I[:16])}),
            ("contact_blind_index_reuses_contact_key", {"index_key": C}),
        )
        for reason, options in cases:
            with self.subTest(reason=reason):
                settings = synthetic_settings(**options)
                with patch.object(contact_encryption, "get_settings", return_value=settings):
                    with self.assertRaises(contact_encryption.ContactEncryptionUnavailable) as raised:
                        contact_encryption.ensure_contact_encryption_available()
                self.assertEqual(raised.exception.reason, reason)

    def test_peer_keys_are_labelled_and_jwt_reuse_is_detected_as_raw_or_base64(self):
        settings = synthetic_settings(
            secret_key=encoded(J),
            messaging_keyring=json.dumps({"retained": encoded(M)}),
        )
        peers = contact_encryption._other_application_keys(settings)
        self.assertIn(("jwt", encoded(J).encode("ascii")), peers)
        self.assertIn(("jwt", J), peers)
        self.assertIn(("messaging", M), peers)
        self.assertTrue(all(label in {"jwt", "messaging"} for label, _ in peers))

        reuse_cases = (
            ("raw JWT bytes", "A" * 32, I, "contact_key_reuses_jwt_key"),
            ("base64 JWT bytes", encoded(C), I, "contact_key_reuses_jwt_key"),
            ("blind index against base64 JWT", encoded(I), I, "contact_key_reuses_jwt_key"),
        )
        for description, secret, index_key, reason in reuse_cases:
            with self.subTest(description=description):
                settings = synthetic_settings(secret_key=secret, index_key=index_key)
                with patch.object(contact_encryption, "get_settings", return_value=settings):
                    with self.assertRaises(contact_encryption.ContactEncryptionUnavailable) as raised:
                        contact_encryption.ensure_contact_encryption_available()
                self.assertEqual(raised.exception.reason, reason)

    def test_messaging_peers_are_compared_even_in_invalid_ring_and_when_inactive(self):
        rings = (
            # The matching key is retained/inactive and followed by bad data.
            {"retired": encoded(C), "broken": "not-base64"},
            # A malformed member comes first; valid peers later in the dict count too.
            {"broken": "not-base64", "retired": encoded(C)},
            # Blind-index reuse is rejected as messaging reuse as well.
            {"old-index": encoded(I), "broken": "not-base64"},
        )
        for ring in rings:
            with self.subTest(ring=ring):
                settings = synthetic_settings(
                    index_key=I,
                    messaging_keyring=json.dumps(ring),
                    messaging_active_id="unrelated-active-id",
                )
                with patch.object(contact_encryption, "get_settings", return_value=settings):
                    with self.assertRaises(contact_encryption.ContactEncryptionUnavailable) as raised:
                        contact_encryption.ensure_contact_encryption_available()
                self.assertEqual(
                    raised.exception.reason,
                    "contact_key_reuses_messaging_key",
                )

    def test_invalid_optional_messaging_rings_do_not_invalidate_contact_material(self):
        invalid_rings = (
            "",
            "{}",
            "[]",
            "not-json",
            '{"current":null}',
            json.dumps({"wrong-length": encoded(M[:16])}),
            json.dumps({"bad-encoding": "%%%"}),
        )
        for ring in invalid_rings:
            with self.subTest(ring=ring):
                settings = synthetic_settings(messaging_keyring=ring)
                self.assertEqual(self.validate_with(settings)[0], "current")
                with patch.object(contact_encryption, "get_settings", return_value=settings):
                    contact_encryption.ensure_contact_encryption_available()

    def test_messaging_validator_remains_fail_closed_for_invalid_rings(self):
        invalid_rings = (
            "",
            "{}",
            "[]",
            "not-json",
            '{"current":null}',
            json.dumps({"wrong-length": encoded(M[:16])}),
            json.dumps({"bad-encoding": "%%%"}),
        )
        for ring in invalid_rings:
            with self.subTest(ring=ring):
                settings = synthetic_settings(messaging_keyring=ring)
                with patch.object(messaging_encryption, "get_settings", return_value=settings):
                    with self.assertRaises(messaging_encryption.MessagingEncryptionUnavailable):
                        messaging_encryption.ensure_encryption_available()

    def test_contact_check_cli_keeps_messaging_warning_optional_and_reports_contact_errors(self):
        path = BACKEND / "scripts" / "check_contact_encryption.py"
        spec = importlib.util.spec_from_file_location(
            "_isolated_contact_encryption_check",
            path,
        )
        cli = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = cli
        self.addCleanup(sys.modules.pop, spec.name, None)
        spec.loader.exec_module(cli)

        ready_output = []
        with patch.object(
            contact_encryption,
            "get_settings",
            return_value=synthetic_settings(messaging_keyring="broken messaging ring"),
        ), patch.object(
            messaging_encryption,
            "get_settings",
            return_value=synthetic_settings(messaging_keyring="broken messaging ring"),
        ), contextlib.redirect_stdout(_ListWriter(ready_output)):
            self.assertEqual(cli.main(), 0)
        self.assertIn("Contact encryption: ready.", "".join(ready_output))
        self.assertIn("Private messaging: unavailable", "".join(ready_output))

        invalid_output = []
        with patch.object(
            contact_encryption,
            "get_settings",
            return_value=synthetic_settings(keyring=""),
        ), patch.object(
            cli,
            "ensure_encryption_available",
        ) as messaging_check, contextlib.redirect_stdout(_ListWriter(invalid_output)):
            self.assertEqual(cli.main(), 1)
        messaging_check.assert_not_called()
        self.assertIn("contact_keyring_missing", "".join(invalid_output))


class _CaptureLogger:
    def __init__(self):
        self.records = []

    def info(self, event, **fields):
        self.records.append(("info", event, fields))

    def error(self, event, **fields):
        self.records.append(("error", event, fields))


class _FakeSession:
    def __init__(self):
        self.closed = False
        self.rolled_back = False

    def close(self):
        self.closed = True

    def rollback(self):
        self.rolled_back = True


class SeedAdminEncryptionTests(unittest.TestCase):
    def load_seed_admin(self):
        logger = _CaptureLogger()
        session = _FakeSession()
        session_factory = Mock(return_value=session)

        logging_stub = types.ModuleType("app.core.logging")
        logging_stub.configure_logging = Mock()
        logging_stub.get_logger = Mock(return_value=logger)

        security_stub = types.ModuleType("app.core.security")
        security_stub.hash_password = Mock(return_value="synthetic-password-hash")
        security_stub.verify_password = Mock(return_value=True)

        db_base_stub = types.ModuleType("app.db.base")
        db_session_stub = types.ModuleType("app.db.session")
        db_session_stub.SessionLocal = session_factory

        repository_stub = types.ModuleType("app.repositories.user_repository")
        repository_stub.UserRepository = Mock()
        auth_stub = types.ModuleType("app.services.auth_service")
        auth_stub.AuthService = Mock()

        replacements = {
            "app.core.logging": logging_stub,
            "app.core.security": security_stub,
            "app.db.base": db_base_stub,
            "app.db.session": db_session_stub,
            "app.repositories.user_repository": repository_stub,
            "app.services.auth_service": auth_stub,
        }
        modules_patch = patch.dict(sys.modules, replacements)
        modules_patch.start()
        self.addCleanup(modules_patch.stop)

        environment_patch = patch.dict(
            os.environ,
            {
                "ADMIN_EMAIL": "synthetic-admin@example.test",
                "ADMIN_PASSWORD": "synthetic-password-long-enough",
            },
            clear=True,
        )
        environment_patch.start()
        self.addCleanup(environment_patch.stop)

        path = BACKEND / "scripts" / "seed_admin.py"
        module_name = "_isolated_seed_admin_contact_test"
        spec = importlib.util.spec_from_file_location(module_name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        self.addCleanup(sys.modules.pop, module_name, None)
        spec.loader.exec_module(module)
        return module, logger, session, session_factory, repository_stub

    def test_contact_preflight_failure_blocks_database_and_sanitizes_diagnostics(self):
        seed, logger, session, session_factory, repository = self.load_seed_admin()
        error = contact_encryption.ContactEncryptionUnavailable(
            "synthetic-secret-keyring-detail-must-not-leak"
        )
        stdout = []
        stderr = []
        with patch.object(seed, "ensure_contact_encryption_available", side_effect=error):
            with contextlib.redirect_stdout(_ListWriter(stdout)), contextlib.redirect_stderr(_ListWriter(stderr)):
                result = seed.main()

        self.assertEqual(result, 1)
        session_factory.assert_not_called()
        repository.UserRepository.assert_not_called()
        self.assertFalse(session.closed)
        self.assertFalse(session.rolled_back)
        self.assertFalse(any(record[1] == "seed.creating_role" for record in logger.records))
        failed = [record for record in logger.records if record[1] == "seed.failed"]
        self.assertEqual(len(failed), 1)
        self.assertEqual(failed[0][2]["error_type"], "ContactEncryptionUnavailable")
        self.assertEqual(
            failed[0][2]["encryption_reason"],
            "contact_configuration_invalid",
        )
        output = "".join(stdout + stderr)
        self.assertIn("contact_configuration_invalid", output)
        self.assertNotIn("synthetic-secret-keyring-detail-must-not-leak", output)
        self.assertNotIn("synthetic-password-long-enough", output)

    def test_valid_contact_with_broken_messaging_reaches_normal_mocked_bootstrap(self):
        seed, logger, session, session_factory, _repository = self.load_seed_admin()
        settings = synthetic_settings(messaging_keyring="malformed-messaging-config")
        statuses = ("created", "verified", "recovered")

        for status in statuses:
            with self.subTest(status=status):
                result = seed.BootstrapResult(
                    status=status,
                    email="synthetic-admin@example.test",
                    user_id=UUID(int=1),
                    is_active=True,
                    has_admin_role=True,
                    credential_matches=True,
                    revoked_refresh_sessions=2 if status == "recovered" else 0,
                )
                bootstrap = Mock(return_value=result)
                seed.bootstrap_admin = bootstrap
                recovery_environment = (
                    {"ADMIN_RECOVERY_CONFIRM": seed.RECOVERY_CONFIRM_VALUE}
                    if status == "recovered"
                    else {}
                )
                output = []
                with patch.dict(os.environ, recovery_environment, clear=False):
                    with patch.object(
                        contact_encryption,
                        "get_settings",
                        return_value=settings,
                    ):
                        with contextlib.redirect_stdout(_ListWriter(output)):
                            exit_code = seed.main()
                self.assertEqual(exit_code, 0)
                bootstrap.assert_called_once()
                self.assertEqual(
                    bootstrap.call_args.kwargs["recover_password"],
                    status == "recovered",
                )
                expected_output = "recovery completed" if status == "recovered" else status
                self.assertIn(expected_output, "".join(output))
        self.assertEqual(session_factory.call_count, 3)
        self.assertTrue(session.closed)
        self.assertFalse(session.rolled_back)
        self.assertFalse(any(record[1] == "seed.failed" for record in logger.records))

    def test_existing_credential_mismatch_still_exits_two_without_recovery(self):
        seed, _logger, _session, _session_factory, _repository = self.load_seed_admin()
        mismatch = seed.BootstrapResult(
            status="verification_requires_attention",
            email="synthetic-admin@example.test",
            user_id=UUID(int=2),
            is_active=True,
            has_admin_role=True,
            credential_matches=False,
        )
        seed.bootstrap_admin = Mock(return_value=mismatch)
        output = []
        with patch.object(
            contact_encryption,
            "get_settings",
            return_value=synthetic_settings(),
        ):
            with contextlib.redirect_stdout(_ListWriter(output)):
                result = seed.main()
        self.assertEqual(result, 2)
        seed.bootstrap_admin.assert_called_once()
        self.assertFalse(seed.bootstrap_admin.call_args.kwargs["recover_password"])
        self.assertIn("needs attention", "".join(output))


class _ListWriter:
    def __init__(self, output):
        self.output = output

    def write(self, value):
        self.output.append(value)
        return len(value)

    def flush(self):
        return None


if __name__ == "__main__":
    unittest.main()