"""add provider favorites

Revision ID: 0c3975715c3b
Revises: e6b7c8d9a012, e8a0f1d37246
Create Date: 2026-09-29 13:53:20.164976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3975715c3b'
down_revision: Union[str, tuple[str, str], None] = ('e6b7c8d9a012', 'e8a0f1d37246')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'provider_id', name='uq_provider_favorites_member_provider')
    )
    op.create_index('ix_provider_favorites_member_created', 'provider_favorites', ['member_id', 'created_at'], unique=False)
    op.create_index('ix_provider_favorites_provider_id', 'provider_favorites', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_favorites_provider_id', table_name='provider_favorites')
    op.drop_index('ix_provider_favorites_member_created', table_name='provider_favorites')
    op.drop_table('provider_favorites')
    # ### end Alembic commands ###
