"""add provider profile updates

Revision ID: 24dd1afe85b3
Revises: ab39f780e1d2
Create Date: 2026-08-21 19:05:05.186081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24dd1afe85b3'
down_revision: Union[str, None] = 'ab39f780e1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    profile_update_status = postgresql.ENUM(
        'PENDING_REVIEW',
        'APPROVED',
        'REJECTED',
        name='provider_profile_update_status',
        create_type=False,
    )
    profile_update_status.create(op.get_bind(), checkfirst=True)
    op.create_table('provider_profile_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('proposed_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', profile_update_status, server_default='PENDING_REVIEW', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index('ix_provider_profile_updates_review_status', 'provider_profile_updates', ['review_status', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_profile_updates_review_status', table_name='provider_profile_updates')
    op.drop_table('provider_profile_updates')
    postgresql.ENUM(
        'PENDING_REVIEW',
        'APPROVED',
        'REJECTED',
        name='provider_profile_update_status',
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
