"""add_specializations_table

Revision ID: 7db4468b7c64
Revises: c4c2e0b50e3d
Create Date: 2026-08-18 13:15:23.590084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db4468b7c64'
down_revision: Union[str, None] = 'c4c2e0b50e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_specializations_name')
    )
    op.create_index('ix_specializations_is_active', 'specializations', ['is_active'], unique=False)
    op.create_index('ix_specializations_name', 'specializations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_specializations_name', table_name='specializations')
    op.drop_index('ix_specializations_is_active', table_name='specializations')
    op.drop_table('specializations')
    # ### end Alembic commands ###
