"""add shared postal lookup rate limits

Revision ID: 8307cdf254f3
Revises: 41bd7a693e20
Create Date: 2026-10-01 04:39:12.050037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8307cdf254f3'
down_revision: Union[str, None] = '41bd7a693e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_lookup_rate_limits',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('attempts', postgresql.ARRAY(sa.DateTime(timezone=True)), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_postal_lookup_rate_limits_expires_at'), 'postal_lookup_rate_limits', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postal_lookup_rate_limits_expires_at'), table_name='postal_lookup_rate_limits')
    op.drop_table('postal_lookup_rate_limits')
    # ### end Alembic commands ###
