"""add_provider_phones_emails

Revision ID: a76f5d02455e
Revises: ff0521730871
Create Date: 2026-08-18 14:14:40.857929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76f5d02455e'
down_revision: Union[str, None] = 'ff0521730871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_emails_provider_id', 'provider_emails', ['provider_id'], unique=False)
    op.create_index('uq_provider_emails_one_primary', 'provider_emails', ['provider_id'], unique=True, postgresql_where=sa.text('is_primary IS true'))
    op.create_table('provider_phones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_phones_provider_id', 'provider_phones', ['provider_id'], unique=False)
    op.create_index('uq_provider_phones_one_primary', 'provider_phones', ['provider_id'], unique=True, postgresql_where=sa.text('is_primary IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_provider_phones_one_primary', table_name='provider_phones', postgresql_where=sa.text('is_primary IS true'))
    op.drop_index('ix_provider_phones_provider_id', table_name='provider_phones')
    op.drop_table('provider_phones')
    op.drop_index('uq_provider_emails_one_primary', table_name='provider_emails', postgresql_where=sa.text('is_primary IS true'))
    op.drop_index('ix_provider_emails_provider_id', table_name='provider_emails')
    op.drop_table('provider_emails')
    # ### end Alembic commands ###
