"""add last successful login timestamp

Revision ID: b35196334e9b
Revises: f7c1d4e8a901
Create Date: 2026-08-21 17:13:50.089596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35196334e9b'
down_revision: Union[str, None] = 'f7c1d4e8a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_successful_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_successful_login_at')
    # ### end Alembic commands ###
