"""add provider reviews

Revision ID: db4631df2e09
Revises: a4f68b20de91
Create Date: 2026-08-21 10:50:49.107541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4631df2e09'
down_revision: Union[str, None] = 'a4f68b20de91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('comment_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_provider_reviews_rating'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'member_id', name='uq_provider_reviews_provider_member')
    )
    op.create_index('ix_provider_reviews_comment_visible', 'provider_reviews', ['comment_visible'], unique=False)
    op.create_index('ix_provider_reviews_created_at', 'provider_reviews', ['created_at'], unique=False)
    op.create_index('ix_provider_reviews_provider_id', 'provider_reviews', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_reviews_provider_id', table_name='provider_reviews')
    op.drop_index('ix_provider_reviews_created_at', table_name='provider_reviews')
    op.drop_index('ix_provider_reviews_comment_visible', table_name='provider_reviews')
    op.drop_table('provider_reviews')
    # ### end Alembic commands ###
