"""add invited provider portal access

Revision ID: f2985f8a52ee
Revises: 8e5d7a1c9b42
Create Date: 2026-08-21 18:33:55.455759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2985f8a52ee'
down_revision: Union[str, None] = '8e5d7a1c9b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_portal_setup_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['provider_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_provider_portal_setup_tokens_invitation_active', 'provider_portal_setup_tokens', ['invitation_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_provider_portal_setup_tokens_invitation_id'), 'provider_portal_setup_tokens', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_provider_portal_setup_tokens_user_id'), 'provider_portal_setup_tokens', ['user_id'], unique=False)
    op.add_column('provider_invitations', sa.Column('portal_user_id', sa.UUID(), nullable=True))
    op.add_column('provider_invitations', sa.Column('portal_access_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(
        'uq_provider_invitations_portal_user_id',
        'provider_invitations',
        ['portal_user_id'],
    )
    op.create_foreign_key(
        'fk_provider_invitations_portal_user_id_users',
        'provider_invitations',
        'users',
        ['portal_user_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    op.drop_constraint('ck_email_delivery_logs_purpose', 'email_delivery_logs', type_='check')
    op.create_check_constraint(
        'ck_email_delivery_logs_purpose',
        'email_delivery_logs',
        "purpose IN ('provider_invitation', 'account_verification', 'provider_portal_access')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_email_delivery_logs_purpose', 'email_delivery_logs', type_='check')
    op.create_check_constraint(
        'ck_email_delivery_logs_purpose',
        'email_delivery_logs',
        "purpose IN ('provider_invitation', 'account_verification')",
    )
    op.drop_constraint(
        'fk_provider_invitations_portal_user_id_users',
        'provider_invitations',
        type_='foreignkey',
    )
    op.drop_constraint(
        'uq_provider_invitations_portal_user_id',
        'provider_invitations',
        type_='unique',
    )
    op.drop_column('provider_invitations', 'portal_access_sent_at')
    op.drop_column('provider_invitations', 'portal_user_id')
    op.drop_index(op.f('ix_provider_portal_setup_tokens_user_id'), table_name='provider_portal_setup_tokens')
    op.drop_index(op.f('ix_provider_portal_setup_tokens_invitation_id'), table_name='provider_portal_setup_tokens')
    op.drop_index('ix_provider_portal_setup_tokens_invitation_active', table_name='provider_portal_setup_tokens')
    op.drop_table('provider_portal_setup_tokens')
    # ### end Alembic commands ###
