"""add_provider_tables

Revision ID: ff0521730871
Revises: 7db4468b7c64
Create Date: 2026-08-18 13:36:04.293632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0521730871'
down_revision: Union[str, None] = '7db4468b7c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('HOSPITAL', 'CLINIC', 'DOCTOR', name='provider_type'), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('visit_stability', sa.Enum('STABLE_VISIT', 'NOT_STABLE_VISIT', name='visit_stability'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='provider_status'), server_default='ACTIVE', nullable=False),
    sa.Column('publication_status', sa.Enum('UNPUBLISHED', 'PUBLISHED', name='publication_status'), server_default='UNPUBLISHED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_name', 'providers', ['name'], unique=False)
    op.create_table('provider_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('address_line_1', sa.String(length=300), nullable=False),
    sa.Column('address_line_2', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('state_province', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_locations_provider_id', 'provider_locations', ['provider_id'], unique=False)
    op.create_index('uq_provider_locations_one_primary', 'provider_locations', ['provider_id'], unique=True, postgresql_where=sa.text('is_primary IS true'))
    op.create_table('provider_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('storage_reference', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_thumbnail', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_photos_provider_id', 'provider_photos', ['provider_id'], unique=False)
    op.create_index('uq_provider_photos_one_thumbnail', 'provider_photos', ['provider_id'], unique=True, postgresql_where=sa.text('is_thumbnail IS true'))
    op.create_table('provider_specializations',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'specialization_id'),
    sa.UniqueConstraint('provider_id', 'specialization_id', name='uq_provider_specializations_provider_specialization')
    )
    op.create_index('ix_provider_specializations_provider_id', 'provider_specializations', ['provider_id'], unique=False)
    op.create_index('ix_provider_specializations_specialization_id', 'provider_specializations', ['specialization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_specializations_specialization_id', table_name='provider_specializations')
    op.drop_index('ix_provider_specializations_provider_id', table_name='provider_specializations')
    op.drop_table('provider_specializations')
    op.drop_index('uq_provider_photos_one_thumbnail', table_name='provider_photos', postgresql_where=sa.text('is_thumbnail IS true'))
    op.drop_index('ix_provider_photos_provider_id', table_name='provider_photos')
    op.drop_table('provider_photos')
    op.drop_index('uq_provider_locations_one_primary', table_name='provider_locations', postgresql_where=sa.text('is_primary IS true'))
    op.drop_index('ix_provider_locations_provider_id', table_name='provider_locations')
    op.drop_table('provider_locations')
    op.drop_index('ix_providers_name', table_name='providers')
    op.drop_table('providers')
    # Drop the PostgreSQL enum types (not handled by drop_table)
    sa.Enum(name='publication_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='provider_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='visit_stability').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='provider_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
